#ifndef MARIO_STATUS_HPP
#define MARIO_STATUS_HPP

enum {
	MARIO_STATUS_FLAG_UNK200      = 0x200,
	MARIO_STATUS_FLAG_RUNNING     = 0x400,
	MARIO_STATUS_FLAG_JUMPING     = 0x800,
	MARIO_STATUS_FLAG_UNK1000     = 0x1000,
	MARIO_STATUS_FLAG_SWIMMING    = 0x2000,
	MARIO_STATUS_FLAG_UNK8000     = 0x8000,
	MARIO_STATUS_FLAG_UNK10000    = 0x10000,
	MARIO_STATUS_FLAG_UNK20000    = 0x20000,
	MARIO_STATUS_FLAG_UNK40000    = 0x40000,
	MARIO_STATUS_FLAG_UNK100000   = 0x100000,
	MARIO_STATUS_FLAG_UNK200000   = 0x200000,
	MARIO_STATUS_FLAG_UNK800000   = 0x800000,
	MARIO_STATUS_FLAG_UNK2000000  = 0x2000000,
	MARIO_STATUS_FLAG_UNK4000000  = 0x4000000,
	MARIO_STATUS_FLAG_UNK8000000  = 0x8000000,
	MARIO_STATUS_FLAG_UNK10000000 = 0x10000000,
	MARIO_STATUS_FLAG_UNK20000000 = 0x20000000,
	MARIO_STATUS_FLAG_UNK80000000 = 0x80000000,

	MARIO_STATUS_TYPE_WAITING  = 0x000,
	MARIO_STATUS_TYPE_RUNNING  = 0x040,
	MARIO_STATUS_TYPE_JUMPING  = 0x080,
	MARIO_STATUS_TYPE_SWIMMING = 0x0C0,
	MARIO_STATUS_TYPE_DEMO     = 0x100,
	MARIO_STATUS_TYPE_SPECIAL  = 0x140,
	MARIO_STATUS_TYPE_ACTION   = 0x180,
	MARIO_STATUS_TYPE_MASK     = 0x1C0,

	// Running
	MARIO_STATUS_RUN = MARIO_STATUS_FLAG_UNK4000000 | MARIO_STATUS_FLAG_RUNNING
	                   | MARIO_STATUS_TYPE_RUNNING | 0x0, // 0x4000440
	MARIO_STATUS_ROTATE_L
	= MARIO_STATUS_FLAG_RUNNING | MARIO_STATUS_TYPE_RUNNING | 0x1, // 0x441
	MARIO_STATUS_ROTATE_R
	= MARIO_STATUS_FLAG_RUNNING | MARIO_STATUS_TYPE_RUNNING | 0x2, // 0x442
	MARIO_STATUS_TURN
	= MARIO_STATUS_FLAG_RUNNING | MARIO_STATUS_TYPE_RUNNING | 0x3, // 0x443
	MARIO_STATUS_TURN_END
	= MARIO_STATUS_FLAG_RUNNING | MARIO_STATUS_TYPE_RUNNING | 0x4, // 0x444
	MARIO_STATUS_BRAKE = MARIO_STATUS_FLAG_UNK4000000
	                     | MARIO_STATUS_FLAG_RUNNING | MARIO_STATUS_TYPE_RUNNING
	                     | 0x5, // 0x4000445
	MARIO_STATUS_SURF = MARIO_STATUS_FLAG_UNK800000 | MARIO_STATUS_FLAG_UNK10000
	                    | MARIO_STATUS_FLAG_RUNNING | MARIO_STATUS_TYPE_RUNNING
	                    | 0x6, // 0x810446
	// TODO: rename, this is like the rail thing in pina park I think?
	MARIO_STATUS_TOROCCO = MARIO_STATUS_FLAG_UNK800000
	                       | MARIO_STATUS_FLAG_RUNNING
	                       | MARIO_STATUS_TYPE_RUNNING | 0x7, // 0x800447
	MARIO_STATUS_WALK_END = MARIO_STATUS_FLAG_UNK4000000
	                        | MARIO_STATUS_FLAG_RUNNING
	                        | MARIO_STATUS_TYPE_RUNNING | 0xA, // 0x400044A
	MARIO_STATUS_SPEED_SLIDING
	= MARIO_STATUS_FLAG_RUNNING | MARIO_STATUS_TYPE_RUNNING | 0xC, // 0x44C
	MARIO_STATUS_FIRE_DASH = MARIO_STATUS_FLAG_UNK20000
	                         | MARIO_STATUS_FLAG_RUNNING
	                         | MARIO_STATUS_TYPE_RUNNING | 0x9, // 0x20449
	MARIO_STATUS_SLIP      = MARIO_STATUS_TYPE_RUNNING | 0x10,  // 0x50
	MARIO_STATUS_SLIP_FORE = MARIO_STATUS_FLAG_UNK800000
	                         | MARIO_STATUS_FLAG_UNK40000
	                         | MARIO_STATUS_FLAG_RUNNING
	                         | MARIO_STATUS_TYPE_RUNNING | 0x12, // 0x840452
	MARIO_STATUS_SLIP_BACK = MARIO_STATUS_FLAG_UNK800000
	                         | MARIO_STATUS_FLAG_UNK40000
	                         | MARIO_STATUS_FLAG_RUNNING
	                         | MARIO_STATUS_TYPE_RUNNING | 0x13, // 0x840453
	MARIO_STATUS_CATCH = MARIO_STATUS_FLAG_UNK800000 | MARIO_STATUS_FLAG_RUNNING
	                     | MARIO_STATUS_TYPE_RUNNING | 0x16, // 0x800456
	MARIO_STATUS_SQUAT_SLIP
	= MARIO_STATUS_FLAG_UNK4000000 | MARIO_STATUS_FLAG_UNK800000
	  | MARIO_STATUS_FLAG_UNK8000 | MARIO_STATUS_FLAG_RUNNING
	  | MARIO_STATUS_TYPE_RUNNING | 0x19, // 0x4808459
	MARIO_STATUS_OIL_RUN = MARIO_STATUS_FLAG_UNK40000
	                       | MARIO_STATUS_FLAG_RUNNING
	                       | MARIO_STATUS_TYPE_RUNNING | 0x1C, // 0x4045C
	MARIO_STATUS_OIL_SLIP = MARIO_STATUS_FLAG_UNK800000
	                        | MARIO_STATUS_FLAG_UNK40000
	                        | MARIO_STATUS_FLAG_RUNNING
	                        | MARIO_STATUS_TYPE_RUNNING | 0x1D, // 0x84045D
	MARIO_STATUS_OIL_SLOPE = MARIO_STATUS_FLAG_UNK40000
	                         | MARIO_STATUS_FLAG_RUNNING
	                         | MARIO_STATUS_TYPE_RUNNING | 0x1E, // 0x4045E
	MARIO_STATUS_BACK_DOWN = MARIO_STATUS_FLAG_UNK20000
	                         | MARIO_STATUS_FLAG_RUNNING
	                         | MARIO_STATUS_TYPE_RUNNING | 0x20, // 0x20460
	MARIO_STATUS_FORE_DOWN = MARIO_STATUS_FLAG_UNK20000
	                         | MARIO_STATUS_FLAG_RUNNING
	                         | MARIO_STATUS_TYPE_RUNNING | 0x21, // 0x20461
	MARIO_STATUS_SHORT_BACK_DOWN
	= MARIO_STATUS_FLAG_UNK20000 | MARIO_STATUS_FLAG_RUNNING
	  | MARIO_STATUS_TYPE_RUNNING | 0x22, // 0x20462
	MARIO_STATUS_SHORT_FORE_DOWN
	= MARIO_STATUS_FLAG_UNK20000 | MARIO_STATUS_FLAG_RUNNING
	  | MARIO_STATUS_TYPE_RUNNING | 0x23, // 0x20463
	MARIO_STATUS_SAFE_BACK_DOWN = MARIO_STATUS_FLAG_UNK20000
	                              | MARIO_STATUS_FLAG_RUNNING
	                              | MARIO_STATUS_TYPE_RUNNING | 0x24, // 0x20464
	MARIO_STATUS_SAFE_FORE_DOWN = MARIO_STATUS_FLAG_UNK20000
	                              | MARIO_STATUS_FLAG_RUNNING
	                              | MARIO_STATUS_TYPE_RUNNING | 0x25, // 0x20465
	MARIO_STATUS_CATCH_DOWN = MARIO_STATUS_FLAG_UNK20000
	                          | MARIO_STATUS_FLAG_RUNNING
	                          | MARIO_STATUS_TYPE_RUNNING | 0x26, // 0x20466
	MARIO_STATUS_LOSER_DOWN = MARIO_STATUS_FLAG_UNK20000
	                          | MARIO_STATUS_FLAG_RUNNING
	                          | MARIO_STATUS_TYPE_RUNNING | 0x27, // 0x20467
	MARIO_STATUS_JUMP_SLIP        = 0x4000470,
	MARIO_STATUS_LAND_SLIP        = 0x4000471,
	MARIO_STATUS_SEC_JUMP_SLIP    = 0x4000472,
	MARIO_STATUS_U_TURN_JUMP_SLIP = 0x4000473,
	MARIO_STATUS_ULTRA_JUMP_SLIP  = 0x4000478,
	MARIO_STATUS_BROAD_JUMP_SLIP  = 0x479,

	// Jumping
	MARIO_STATUS_JUMP = MARIO_STATUS_FLAG_UNK2000000 | MARIO_STATUS_FLAG_JUMPING
	                    | MARIO_STATUS_TYPE_JUMPING | 0x0, // 0x2000880
	MARIO_STATUS_SECOND_JUMP = MARIO_STATUS_FLAG_UNK2000000
	                           | MARIO_STATUS_FLAG_JUMPING
	                           | MARIO_STATUS_TYPE_JUMPING | 0x1, // 0x2000881
	MARIO_STATUS_ULTRA_JUMP
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x2, // 0x882
	MARIO_STATUS_BACK_JUMP
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x3, // 0x883
	MARIO_STATUS_FORCE_JUMP
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x4, // 0x884
	MARIO_STATUS_WALL_JUMP = MARIO_STATUS_FLAG_UNK2000000
	                         | MARIO_STATUS_FLAG_JUMPING
	                         | MARIO_STATUS_TYPE_JUMPING | 0x6, // 0x2000886
	MARIO_STATUS_MISS_JUMP = MARIO_STATUS_FLAG_UNK2000000
	                         | MARIO_STATUS_FLAG_JUMPING
	                         | MARIO_STATUS_TYPE_JUMPING | 0x5, // 0x2000885
	MARIO_STATUS_U_TURN_JUMP
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x7, // 0x887
	MARIO_STATUS_BROAD_JUMP
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x8, // 0x888
	MARIO_STATUS_ROTATE_BROAD_JUMP
	= MARIO_STATUS_FLAG_UNK2000000 | MARIO_STATUS_FLAG_JUMPING
	  | MARIO_STATUS_TYPE_JUMPING | 0x9, // 0x2000889
	// NOTE: colloquially known as the "dive jump"
	MARIO_STATUS_JUMP_CATCH = MARIO_STATUS_FLAG_UNK800000
	                          | MARIO_STATUS_FLAG_JUMPING
	                          | MARIO_STATUS_TYPE_JUMPING | 0xA, // 0x80088A
	MARIO_STATUS_ROCKET
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0xB, // 0x88B
	MARIO_STATUS_LANDING
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0xC, // 0x88C
	MARIO_STATUS_ROCKET_LANDING
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0xD, // 0x88D
	MARIO_STATUS_SLIP_FALL = MARIO_STATUS_FLAG_UNK2000000
	                         | MARIO_STATUS_FLAG_JUMPING
	                         | MARIO_STATUS_TYPE_JUMPING | 0xE, // 0x200088E
	MARIO_STATUS_TRAMPLE = MARIO_STATUS_FLAG_UNK2000000
	                       | MARIO_STATUS_FLAG_JUMPING
	                       | MARIO_STATUS_TYPE_JUMPING | 0x10, // 0x2000890
	MARIO_STATUS_DIVE
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x11, // 0x891
	MARIO_STATUS_WIRE_JUMP
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x12, // 0x892
	MARIO_STATUS_WIRE_ROLL_JUMP
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x13, // 0x893
	MARIO_STATUS_PULL_JUMP
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x14, // 0x894
	MARIO_STATUS_LEFT_ROTATE_JUMP
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x15, // 0x895
	MARIO_STATUS_RIGHT_ROTATE_JUMP
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x16, // 0x896
	MARIO_STATUS_CATCH_STOP
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x26, // 0x8A6
	MARIO_STATUS_WALL_SLIDE
	= MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_JUMPING | 0x27, // 0x8A7
	MARIO_STATUS_HIP_DROP = MARIO_STATUS_FLAG_UNK800000
	                        | MARIO_STATUS_FLAG_JUMPING
	                        | MARIO_STATUS_TYPE_JUMPING | 0x29, // 0x8008A9
	MARIO_STATUS_JUMP_THROW = MARIO_STATUS_FLAG_UNK80000000
	                          | MARIO_STATUS_FLAG_UNK2000000
	                          | MARIO_STATUS_FLAG_JUMPING
	                          | MARIO_STATUS_TYPE_JUMPING | 0x2B, // 0x820008AB
	MARIO_STATUS_JUMP_SHORT_BACK_DOWN
	= MARIO_STATUS_FLAG_UNK20000 | MARIO_STATUS_FLAG_JUMPING
	  | MARIO_STATUS_TYPE_JUMPING | 0x30, // 0x208B0
	MARIO_STATUS_JUMP_SHORT_FORE_DOWN
	= MARIO_STATUS_FLAG_UNK20000 | MARIO_STATUS_FLAG_JUMPING
	  | MARIO_STATUS_TYPE_JUMPING | 0x31, // 0x208B1
	MARIO_STATUS_JUMP_FORE_DOWN = MARIO_STATUS_FLAG_UNK20000
	                              | MARIO_STATUS_FLAG_JUMPING
	                              | MARIO_STATUS_TYPE_JUMPING | 0x32, // 0x208B2
	MARIO_STATUS_JUMP_BACK_DOWN = MARIO_STATUS_FLAG_UNK20000
	                              | MARIO_STATUS_FLAG_JUMPING
	                              | MARIO_STATUS_TYPE_JUMPING | 0x33, // 0x208B3
	MARIO_STATUS_FIRE_JUMP = MARIO_STATUS_FLAG_UNK20000
	                         | MARIO_STATUS_FLAG_JUMPING
	                         | MARIO_STATUS_TYPE_JUMPING | 0x34, // 0x208B4
	MARIO_STATUS_FIRE_LAND = MARIO_STATUS_FLAG_UNK20000
	                         | MARIO_STATUS_FLAG_JUMPING
	                         | MARIO_STATUS_TYPE_JUMPING | 0x35, // 0x208B5
	MARIO_STATUS_LAND_SAFE_DOWN = MARIO_STATUS_FLAG_UNK20000
	                              | MARIO_STATUS_FLAG_JUMPING
	                              | MARIO_STATUS_TYPE_JUMPING | 0x36, // 0x208B6
	MARIO_STATUS_FIRE_DOWN = MARIO_STATUS_FLAG_UNK20000
	                         | MARIO_STATUS_FLAG_JUMPING
	                         | MARIO_STATUS_TYPE_JUMPING | 0x37, // 0x208B7
	MARIO_STATUS_THROWN_DOWN = MARIO_STATUS_FLAG_UNK20000
	                           | MARIO_STATUS_FLAG_JUMPING
	                           | MARIO_STATUS_TYPE_JUMPING | 0x38, // 0x208B8
	MARIO_STATUS_FALL_DEAD = MARIO_STATUS_FLAG_UNK20000
	                         | MARIO_STATUS_FLAG_JUMPING
	                         | MARIO_STATUS_TYPE_JUMPING | 0x39, // 0x208B9
	MARIO_STATUS_WIRE_HANG_LAND_SAFE_DOWN
	= MARIO_STATUS_FLAG_UNK20000 | MARIO_STATUS_FLAG_JUMPING
	  | MARIO_STATUS_TYPE_JUMPING | 0x3A, // 0x208BA

	// Waiting
	MARIO_STATUS_WAIT            = 0xC400201,
	MARIO_STATUS_SLEEPY          = 0xC400202,
	MARIO_STATUS_SLEEP           = 0xC000203,
	MARIO_STATUS_WAKEUP          = 0xC000204,
	MARIO_STATUS_SQUAT           = 0xC008220,
	MARIO_STATUS_SQUAT_START     = 0xC008221,
	MARIO_STATUS_SQUAT_STANDUP   = 0xC008222,
	MARIO_STATUS_THROWN_END      = 0xC000223,
	MARIO_STATUS_PULL_END        = 0xC00022F,
	MARIO_STATUS_JUMP_END        = 0xC000230,
	MARIO_STATUS_SEC_JUMP_END    = 0xC000231,
	MARIO_STATUS_LAND_END        = 0xC000232,
	MARIO_STATUS_U_TURN_JUMP_END = 0xC000233,
	MARIO_STATUS_JUMP_THROW_END  = 0x80000A36,
	MARIO_STATUS_FIRE_JUMP_END   = 0x8000239,
	MARIO_STATUS_ULTRA_JUMP_END  = 0x800023A,
	MARIO_STATUS_BROAD_JUMP_END  = 0x800023B,
	MARIO_STATUS_HIP_ATTACK_END  = 0x80023C,
	MARIO_STATUS_BRAKE_END       = 0xC00023D,
	MARIO_STATUS_SLIP_END        = 0xC00023E,

	// Swimming
	MARIO_STATUS_SWIM_START = MARIO_STATUS_FLAG_SWIMMING
	                          | MARIO_STATUS_FLAG_UNK200
	                          | MARIO_STATUS_TYPE_SWIMMING | 0x11, // 0x22D1
	MARIO_STATUS_SWIM_WAIT = MARIO_STATUS_FLAG_SWIMMING
	                         | MARIO_STATUS_FLAG_UNK200
	                         | MARIO_STATUS_TYPE_SWIMMING | 0x12, // 0x22D2
	MARIO_STATUS_SWIM_WAIT_TO_PADDLE
	= MARIO_STATUS_FLAG_SWIMMING | MARIO_STATUS_FLAG_RUNNING
	  | MARIO_STATUS_TYPE_SWIMMING | 0x13, // 0x24D3
	MARIO_STATUS_SWIM_PADDLE_START
	= MARIO_STATUS_FLAG_SWIMMING | MARIO_STATUS_FLAG_RUNNING
	  | MARIO_STATUS_TYPE_SWIMMING | 0x14, // 0x24D4
	MARIO_STATUS_SWIM_PADDLE = MARIO_STATUS_FLAG_SWIMMING
	                           | MARIO_STATUS_FLAG_RUNNING
	                           | MARIO_STATUS_TYPE_SWIMMING | 0x15, // 0x24D5
	MARIO_STATUS_SWIM_PADDLE_END
	= MARIO_STATUS_FLAG_SWIMMING | MARIO_STATUS_FLAG_RUNNING
	  | MARIO_STATUS_TYPE_SWIMMING | 0x16, // 0x24D6
	MARIO_STATUS_SWIM_PADDLE_END_TO_WAIT
	= MARIO_STATUS_FLAG_SWIMMING | MARIO_STATUS_FLAG_RUNNING
	  | MARIO_STATUS_TYPE_SWIMMING | 0x17, // 0x24D7
	MARIO_STATUS_SWIM_UP = MARIO_STATUS_FLAG_SWIMMING
	                       | MARIO_STATUS_FLAG_RUNNING
	                       | MARIO_STATUS_TYPE_SWIMMING | 0x18, // 0x24D8
	MARIO_STATUS_SWIM_DIVE = MARIO_STATUS_FLAG_SWIMMING
	                         | MARIO_STATUS_FLAG_RUNNING
	                         | MARIO_STATUS_TYPE_SWIMMING | 0x19, // 0x24D9
	MARIO_STATUS_SWIM_P_DAMAGE = MARIO_STATUS_FLAG_SWIMMING
	                             | MARIO_STATUS_FLAG_RUNNING
	                             | MARIO_STATUS_TYPE_SWIMMING | 0x1A, // 0x24DA
	MARIO_STATUS_SWIM_DOWN = MARIO_STATUS_FLAG_UNK20000
	                         | MARIO_STATUS_FLAG_SWIMMING
	                         | MARIO_STATUS_FLAG_RUNNING
	                         | MARIO_STATUS_TYPE_SWIMMING | 0x20, // 0x224E0
	MARIO_STATUS_SWIM_P_DOWN = MARIO_STATUS_FLAG_UNK20000
	                           | MARIO_STATUS_FLAG_SWIMMING
	                           | MARIO_STATUS_FLAG_RUNNING
	                           | MARIO_STATUS_TYPE_SWIMMING | 0x21, // 0x224E1

	// Special
	// Note that the "bars" here are actually trees/palms
	MARIO_STATUS_BAR_WAIT
	= MARIO_STATUS_FLAG_UNK10000000 | MARIO_STATUS_FLAG_UNK8000000
	  | MARIO_STATUS_FLAG_UNK100000 | MARIO_STATUS_FLAG_UNK200
	  | MARIO_STATUS_TYPE_SPECIAL | 0x0, // 0x18100340
	MARIO_STATUS_BAR_HANG = MARIO_STATUS_FLAG_UNK10000000
	                        | MARIO_STATUS_FLAG_UNK100000
	                        | MARIO_STATUS_FLAG_UNK200
	                        | MARIO_STATUS_TYPE_SPECIAL | 0x1, // 0x10100341
	MARIO_STATUS_BAR_CLIMB = MARIO_STATUS_FLAG_UNK10000000
	                         | MARIO_STATUS_FLAG_UNK100000
	                         | MARIO_STATUS_FLAG_UNK200
	                         | MARIO_STATUS_TYPE_SPECIAL | 0x3, // 0x10100343
	MARIO_STATUS_KICK_ROOF_ROLL_UP
	= MARIO_STATUS_FLAG_UNK200000 | MARIO_STATUS_FLAG_UNK200
	  | MARIO_STATUS_TYPE_SPECIAL | 0x5, // 0x200345
	MARIO_STATUS_KICK_ROOF_ROLL_DOWN
	= MARIO_STATUS_FLAG_UNK200000 | MARIO_STATUS_FLAG_UNK200
	  | MARIO_STATUS_TYPE_SPECIAL | 0x6, // 0x200346
	MARIO_STATUS_KICK_ROOF = MARIO_STATUS_FLAG_UNK200000
	                         | MARIO_STATUS_FLAG_UNK200
	                         | MARIO_STATUS_TYPE_SPECIAL | 0x7, // 0x200347
	MARIO_STATUS_HANG_ROOF
	= MARIO_STATUS_FLAG_UNK8000000 | MARIO_STATUS_FLAG_UNK200000
	  | MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_SPECIAL | 0x8, // 0x8200348
	MARIO_STATUS_WAIT_ROOF = MARIO_STATUS_FLAG_UNK200000
	                         | MARIO_STATUS_FLAG_UNK200
	                         | MARIO_STATUS_TYPE_SPECIAL | 0x9, // 0x200349
	MARIO_STATUS_MOVE_ROOF = MARIO_STATUS_FLAG_UNK200000
	                         | MARIO_STATUS_FLAG_RUNNING
	                         | MARIO_STATUS_TYPE_SPECIAL | 0xA, // 0x20054A
	MARIO_STATUS_HANGING
	= MARIO_STATUS_FLAG_UNK20000000 | MARIO_STATUS_FLAG_UNK10000000
	  | MARIO_STATUS_FLAG_UNK8000000 | MARIO_STATUS_FLAG_UNK200
	  | MARIO_STATUS_TYPE_SPECIAL | 0xB, // 0x3800034B
	MARIO_STATUS_ASCEND = MARIO_STATUS_FLAG_UNK20000000
	                      | MARIO_STATUS_FLAG_UNK10000000
	                      | MARIO_STATUS_FLAG_RUNNING
	                      | MARIO_STATUS_TYPE_SPECIAL | 0xC, // 0x3000054C
	MARIO_STATUS_DESCEND = MARIO_STATUS_FLAG_UNK20000000
	                       | MARIO_STATUS_FLAG_UNK10000000
	                       | MARIO_STATUS_FLAG_RUNNING
	                       | MARIO_STATUS_TYPE_SPECIAL | 0xE, // 0x3000054E
	MARIO_STATUS_HANG_JUMPING = MARIO_STATUS_FLAG_UNK20000000
	                            | MARIO_STATUS_FLAG_UNK10000000
	                            | MARIO_STATUS_FLAG_RUNNING
	                            | MARIO_STATUS_TYPE_SPECIAL | 0xF, // 0x3000054F
	MARIO_STATUS_WIRE_WAIT
	= MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_SPECIAL | 0x10, // 0x350
	MARIO_STATUS_WIRE_S_WAIT
	= MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_SPECIAL | 0x11, // 0x351
	MARIO_STATUS_WIRE_WAIT_TO_S_WAIT_L
	= MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_SPECIAL | 0x12, // 0x352
	MARIO_STATUS_WIRE_WAIT_TO_S_WAIT_R
	= MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_SPECIAL | 0x13, // 0x353
	MARIO_STATUS_WIRE_WAIT_TO_HANG
	= MARIO_STATUS_FLAG_UNK10000000 | MARIO_STATUS_FLAG_RUNNING
	  | MARIO_STATUS_TYPE_SPECIAL | 0x14, // 0x10000554
	MARIO_STATUS_WIRE_S_WAIT_TO_HANG
	= MARIO_STATUS_FLAG_UNK10000000 | MARIO_STATUS_FLAG_RUNNING
	  | MARIO_STATUS_TYPE_SPECIAL | 0x15, // 0x10000555
	MARIO_STATUS_WIRE_RETURN = MARIO_STATUS_FLAG_UNK10000000
	                           | MARIO_STATUS_FLAG_RUNNING
	                           | MARIO_STATUS_TYPE_SPECIAL | 0x16, // 0x10000556
	MARIO_STATUS_WIRE_HANGING
	= MARIO_STATUS_FLAG_UNK10000000 | MARIO_STATUS_FLAG_UNK200
	  | MARIO_STATUS_TYPE_SPECIAL | 0x17, // 0x10000357
	MARIO_STATUS_WIRE_ROLLING
	= MARIO_STATUS_FLAG_UNK10000000 | MARIO_STATUS_FLAG_UNK200
	  | MARIO_STATUS_TYPE_SPECIAL | 0x18, // 0x10000358
	MARIO_STATUS_WIRE_S_WAIT_TO_WAIT_R
	= MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_SPECIAL | 0x1B, // 0x35B
	MARIO_STATUS_WIRE_S_WAIT_TO_WAIT_L
	= MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_SPECIAL | 0x1C, // 0x35C
	MARIO_STATUS_PULLING
	= MARIO_STATUS_FLAG_RUNNING | MARIO_STATUS_TYPE_SPECIAL | 0x20, // 0x560
	MARIO_STATUS_OIL_PULLING = MARIO_STATUS_FLAG_UNK40000
	                           | MARIO_STATUS_FLAG_RUNNING
	                           | MARIO_STATUS_TYPE_SPECIAL | 0x21, // 0x40561
	MARIO_STATUS_FENCE_MOVE
	= MARIO_STATUS_FLAG_UNK20000000 | MARIO_STATUS_FLAG_UNK10000000
	  | MARIO_STATUS_FLAG_UNK8000000 | MARIO_STATUS_FLAG_UNK200
	  | MARIO_STATUS_TYPE_SPECIAL | 0x28, // 0x38000368
	MARIO_STATUS_FENCE_PUNCH = MARIO_STATUS_FLAG_UNK20000000
	                           | MARIO_STATUS_FLAG_UNK10000000
	                           | MARIO_STATUS_FLAG_UNK200
	                           | MARIO_STATUS_TYPE_SPECIAL | 0x2A, // 0x3000036A
	MARIO_STATUS_FENCE_CATCH = MARIO_STATUS_FLAG_UNK20000000
	                           | MARIO_STATUS_FLAG_UNK10000000
	                           | MARIO_STATUS_FLAG_UNK200
	                           | MARIO_STATUS_TYPE_SPECIAL | 0x2B, // 0x3000036B
	MARIO_STATUS_FENCE_JUMP_CATCH
	= MARIO_STATUS_FLAG_UNK20000000 | MARIO_STATUS_FLAG_UNK10000000
	  | MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_SPECIAL
	  | 0x2C, // 0x3000036C
	MARIO_STATUS_TAKEN = MARIO_STATUS_FLAG_UNK10000000
	                     | MARIO_STATUS_FLAG_UNK20000 | MARIO_STATUS_FLAG_UNK200
	                     | MARIO_STATUS_TYPE_SPECIAL | 0x30, // 0x10020370

	// Actions
	MARIO_STATUS_TAKE
	= MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_ACTION | 0x3, // 0x383
	MARIO_STATUS_TAKE_POSE
	= MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_ACTION | 0x4, // 0x384
	MARIO_STATUS_CATCH_LOST
	= MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_ACTION | 0x6, // 0x386
	MARIO_STATUS_PUTTING = MARIO_STATUS_FLAG_UNK80000000
	                       | MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_ACTION
	                       | 0x7, // 0x80000387
	MARIO_STATUS_PITCHING = MARIO_STATUS_FLAG_UNK80000000
	                        | MARIO_STATUS_FLAG_RUNNING
	                        | MARIO_STATUS_TYPE_ACTION | 0x8, // 0x80000588

	// Autodemo
	MARIO_STATUS_WIN_DEMO = MARIO_STATUS_FLAG_UNK1000 | MARIO_STATUS_FLAG_UNK200
	                        | MARIO_STATUS_TYPE_DEMO | 0x02,
	MARIO_STATUS_READ_BILLBOARD
	= MARIO_STATUS_FLAG_UNK10000000 | MARIO_STATUS_FLAG_UNK1000
	  | MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_DEMO | 0x08,
	MARIO_STATUS_BOTTLE_IN = MARIO_STATUS_FLAG_UNK1000
	                         | MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_DEMO
	                         | 0x10,
	MARIO_STATUS_ELEC_DOWN
	= MARIO_STATUS_FLAG_UNK20000 | MARIO_STATUS_FLAG_UNK1000
	  | MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_DEMO | 0x13,
	MARIO_STATUS_DOOR_OPEN_R = MARIO_STATUS_FLAG_UNK1000
	                           | MARIO_STATUS_FLAG_UNK200
	                           | MARIO_STATUS_TYPE_DEMO | 0x20,
	MARIO_STATUS_DOOR_OPEN_L = MARIO_STATUS_FLAG_UNK1000
	                           | MARIO_STATUS_FLAG_UNK200
	                           | MARIO_STATUS_TYPE_DEMO | 0x21,
	MARIO_STATUS_SINK_LOSER = MARIO_STATUS_FLAG_UNK10000000
	                          | MARIO_STATUS_FLAG_UNK1000
	                          | MARIO_STATUS_TYPE_DEMO | 0x23,
	MARIO_STATUS_DOWN_LOSER
	= MARIO_STATUS_FLAG_UNK10000000 | MARIO_STATUS_FLAG_UNK1000
	  | MARIO_STATUS_FLAG_JUMPING | MARIO_STATUS_TYPE_DEMO | 0x2A,
	MARIO_STATUS_WARP_OUT = MARIO_STATUS_FLAG_UNK1000 | MARIO_STATUS_FLAG_UNK200
	                        | MARIO_STATUS_TYPE_DEMO | 0x37,
	MARIO_STATUS_WARP_IN = MARIO_STATUS_FLAG_UNK1000 | MARIO_STATUS_FLAG_UNK200
	                       | MARIO_STATUS_TYPE_DEMO | 0x36,
	MARIO_STATUS_ELECTRIC_DAMAGE = MARIO_STATUS_FLAG_UNK20000
	                               | MARIO_STATUS_FLAG_UNK200
	                               | MARIO_STATUS_TYPE_DEMO | 0x38,
	MARIO_STATUS_FOOT_DOWN = MARIO_STATUS_FLAG_UNK20000
	                         | MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_DEMO
	                         | 0x3C,
	MARIO_STATUS_NOMOTION = MARIO_STATUS_FLAG_UNK1000 | MARIO_STATUS_FLAG_UNK200
	                        | MARIO_STATUS_TYPE_DEMO | 0x3E,
	MARIO_STATUS_DISAPPEAR = MARIO_STATUS_FLAG_UNK1000
	                         | MARIO_STATUS_FLAG_UNK200 | MARIO_STATUS_TYPE_DEMO
	                         | 0x3F,

	MARIO_STATUS_ID_MASK = 0x3F,

	MARIO_STATUS_TYPE_AND_ID_MASK = 0x1FF,
};

#endif
