O_FILES :=                                                            \
	$(BUILD_DIR)/src/main.o                                           \
    $(BUILD_DIR)/asm/JSystem/JKRArchivePri.o                          \
    $(BUILD_DIR)/asm/JSystem/JKRAramArchive.o                         \
    $(BUILD_DIR)/asm/JSystem/JKRAramHeap.o                            \
    $(BUILD_DIR)/asm/JSystem/JKRAram.o                                \
    $(BUILD_DIR)/asm/JSystem/JKRArchivePub.o                          \
    $(BUILD_DIR)/asm/JSystem/JKRCompArchive.o                         \
    $(BUILD_DIR)/asm/JSystem/JKRDisposer.o                            \
    $(BUILD_DIR)/asm/JSystem/JKRDvdArchive.o                          \
    $(BUILD_DIR)/asm/JSystem/JKRDvdFile.o                             \
    $(BUILD_DIR)/asm/JSystem/JKRExpHeap.o                             \
    $(BUILD_DIR)/asm/JSystem/JKRFileCache.o                           \
    $(BUILD_DIR)/asm/JSystem/JKRFileFinder.o                          \
    $(BUILD_DIR)/asm/JSystem/JKRFileLoader.o                          \
    $(BUILD_DIR)/asm/JSystem/JKRHeap.o                                \
    $(BUILD_DIR)/asm/JSystem/JKRMemArchive.o                          \
    $(BUILD_DIR)/asm/JSystem/JKRSolidHeap.o                           \
    $(BUILD_DIR)/asm/JSystem/JKRStdHeap.o                             \
    $(BUILD_DIR)/asm/JSystem/JKRThread.o                              \
    $(BUILD_DIR)/asm/JSystem/JSUOutputStream.o                        \
    $(BUILD_DIR)/asm/JSystem/JSUInputStream.o                         \
    $(BUILD_DIR)/asm/JSystem/JSUList.o                                \
    $(BUILD_DIR)/asm/JSystem/JSUMemoryStream.o                        \
    $(BUILD_DIR)/asm/JSystem/JSUFileStream.o                          \
    $(BUILD_DIR)/asm/JSystem/JUTException.o                           \
    $(BUILD_DIR)/asm/JSystem/JUTDirectPrint.o                         \
    $(BUILD_DIR)/asm/JSystem/JUTDbPrint.o                             \
    $(BUILD_DIR)/asm/JSystem/JUTFont.o                                \
    $(BUILD_DIR)/asm/JSystem/JUTGamePad.o                             \
    $(BUILD_DIR)/asm/JSystem/JUTNameTab.o                             \
    $(BUILD_DIR)/asm/JSystem/JUTPalette.o                             \
    $(BUILD_DIR)/src/JSystem/JUTRect.o                                \
    $(BUILD_DIR)/asm/JSystem/JUTResource.o                            \
    $(BUILD_DIR)/asm/JSystem/JUTTexture.o                             \
    $(BUILD_DIR)/asm/JSystem/JMath.o                                  \
    $(BUILD_DIR)/asm/JSystem/J2DPane.o                                \
    $(BUILD_DIR)/asm/JSystem/J2DPicture.o                             \
    $(BUILD_DIR)/asm/JSystem/J2DPrint.o                               \
    $(BUILD_DIR)/asm/JSystem/J2DScreen.o                              \
    $(BUILD_DIR)/asm/JSystem/J2DTextBox.o                             \
    $(BUILD_DIR)/asm/JSystem/J2DWindow.o                              \
    $(BUILD_DIR)/asm/JSystem/J3DTransform.o                           \
    $(BUILD_DIR)/asm/JSystem/J3DCluster.o                             \
    $(BUILD_DIR)/asm/JSystem/J3DJoint.o                               \
    $(BUILD_DIR)/asm/JSystem/J3DMaterial.o                            \
    $(BUILD_DIR)/asm/JSystem/J3DModel.o                               \
    $(BUILD_DIR)/asm/JSystem/J3DNode.o                                \
    $(BUILD_DIR)/asm/JSystem/J3DShape.o                               \
    $(BUILD_DIR)/asm/JSystem/J3DSys.o                                 \
    $(BUILD_DIR)/asm/JSystem/J3DAnimation.o                           \
    $(BUILD_DIR)/asm/JSystem/J3DClusterLoader.o                       \
    $(BUILD_DIR)/asm/JSystem/J3DJointFactory.o                        \
    $(BUILD_DIR)/asm/JSystem/J3DMaterialFactory.o                     \
    $(BUILD_DIR)/asm/JSystem/J3DModelLoader.o                         \
    $(BUILD_DIR)/asm/JSystem/J3DShapeFactory.o                        \
    $(BUILD_DIR)/asm/JSystem/J3DAnmLoader.o                           \
    $(BUILD_DIR)/asm/JSystem/std-list.o                               \
    $(BUILD_DIR)/asm/JSystem/JKRDvdRipper.o                           \
    $(BUILD_DIR)/asm/JSystem/J2DGrafContext.o                         \
    $(BUILD_DIR)/asm/JSystem/JKRDvdAramRipper.o                       \
    $(BUILD_DIR)/asm/JSystem/JKRDecomp.o                              \
    $(BUILD_DIR)/asm/JSystem/J2DOrthoGraph.o                          \
    $(BUILD_DIR)/asm/JSystem/J3DVertex.o                              \
    $(BUILD_DIR)/asm/JSystem/J3DPacket.o                              \
    $(BUILD_DIR)/asm/JSystem/J3DTevs.o                                \
    $(BUILD_DIR)/asm/JSystem/J3DDrawBuffer.o                          \
    $(BUILD_DIR)/asm/JSystem/J3DMaterialAnm.o                         \
    $(BUILD_DIR)/asm/JSystem/std-vector.o                             \
    $(BUILD_DIR)/asm/JSystem/JKRAramBlock.o                           \
    $(BUILD_DIR)/asm/JSystem/JKRAramPiece.o                           \
    $(BUILD_DIR)/asm/JSystem/JKRAramStream.o                          \
    $(BUILD_DIR)/asm/JSystem/JUTAssert.o                              \
    $(BUILD_DIR)/asm/JSystem/JUTVideo.o                               \
    $(BUILD_DIR)/asm/JSystem/JUTResFont.o                             \
    $(BUILD_DIR)/asm/JSystem/JUTRomFont.o                             \
    $(BUILD_DIR)/asm/JSystem/JRenderer.o                              \
    $(BUILD_DIR)/asm/JSystem/JUTConsole.o                             \
    $(BUILD_DIR)/asm/JSystem/JUTDirectFile.o                          \
    $(BUILD_DIR)/asm/JSystem/linklist.o                               \
    $(BUILD_DIR)/asm/JSystem/singlelinklist.o                         \
    $(BUILD_DIR)/asm/JSystem/JDRActor.o                               \
    $(BUILD_DIR)/asm/JSystem/JDRCamera.o                              \
    $(BUILD_DIR)/asm/JSystem/JDRCharacter.o                           \
    $(BUILD_DIR)/asm/JSystem/JDRDirector.o                            \
    $(BUILD_DIR)/asm/JSystem/JDRDisplay.o                             \
    $(BUILD_DIR)/asm/JSystem/JDRDrawBufObj.o                          \
    $(BUILD_DIR)/asm/JSystem/JDRDStage.o                              \
    $(BUILD_DIR)/asm/JSystem/JDRDStageGroup.o                         \
    $(BUILD_DIR)/asm/JSystem/JDREfbCtrl.o                             \
    $(BUILD_DIR)/asm/JSystem/JDREfbSetting.o                          \
    $(BUILD_DIR)/asm/JSystem/JDRFrmGXSet.o                            \
    $(BUILD_DIR)/asm/JSystem/JDRGraphics.o                            \
    $(BUILD_DIR)/asm/JSystem/JDRLighting.o                            \
    $(BUILD_DIR)/asm/JSystem/JDRNameRef.o                             \
    $(BUILD_DIR)/asm/JSystem/JDRNameRefGen.o                          \
    $(BUILD_DIR)/src/JSystem/JDRPlacement.o                           \
    $(BUILD_DIR)/asm/JSystem/JDRRenderMode.o                          \
    $(BUILD_DIR)/src/JSystem/JDRResolution.o                          \
    $(BUILD_DIR)/asm/JSystem/JDRScreen.o                              \
    $(BUILD_DIR)/asm/JSystem/JDRSmJ3DAct.o                            \
    $(BUILD_DIR)/asm/JSystem/JDRSmJ3DScn.o                            \
    $(BUILD_DIR)/asm/JSystem/JDRVideo.o                               \
    $(BUILD_DIR)/asm/JSystem/JDRViewConnecter.o                       \
    $(BUILD_DIR)/asm/JSystem/JDRViewObj.o                             \
    $(BUILD_DIR)/asm/JSystem/JDRViewport.o                            \
    $(BUILD_DIR)/asm/JSystem/JADHioNode.o                             \
    $(BUILD_DIR)/asm/JSystem/JALCalc.o                                \
    $(BUILD_DIR)/asm/JSystem/JALModSe.o                               \
    $(BUILD_DIR)/asm/JSystem/JAIAnimation.o                           \
    $(BUILD_DIR)/asm/JSystem/JAIAsnData.o                             \
    $(BUILD_DIR)/asm/JSystem/JAIBasic.o                               \
    $(BUILD_DIR)/asm/JSystem/JAIConst.o                               \
    $(BUILD_DIR)/asm/JSystem/JAIData.o                                \
    $(BUILD_DIR)/asm/JSystem/JAIDebug.o                               \
    $(BUILD_DIR)/asm/JSystem/JAIEntry.o                               \
    $(BUILD_DIR)/asm/JSystem/JAIEntrySe.o                             \
    $(BUILD_DIR)/asm/JSystem/JAIEntrySequence.o                       \
    $(BUILD_DIR)/asm/JSystem/JAIEntryStream.o                         \
    $(BUILD_DIR)/asm/JSystem/JAIGFrameSe.o                            \
    $(BUILD_DIR)/asm/JSystem/JAIGFrameSequence.o                      \
    $(BUILD_DIR)/asm/JSystem/JAIGFrameStream.o                        \
    $(BUILD_DIR)/asm/JSystem/JAIGlobalParameter.o                     \
    $(BUILD_DIR)/asm/JSystem/JAISound.o                               \
    $(BUILD_DIR)/asm/JSystem/JAISystemInterface.o                     \
    $(BUILD_DIR)/asm/JSystem/JASBank.o                                \
    $(BUILD_DIR)/asm/JSystem/JASBankMgr.o                             \
    $(BUILD_DIR)/asm/JSystem/JASBasicBank.o                           \
    $(BUILD_DIR)/asm/JSystem/JASBasicInst.o                           \
    $(BUILD_DIR)/asm/JSystem/JASBasicWaveBank.o                       \
    $(BUILD_DIR)/asm/JSystem/JASBNKParser.o                           \
    $(BUILD_DIR)/asm/JSystem/JASDrumSet.o                             \
    $(BUILD_DIR)/asm/JSystem/JASInstEffect.o                          \
    $(BUILD_DIR)/asm/JSystem/JASInstRand.o                            \
    $(BUILD_DIR)/asm/JSystem/JASInstSense.o                           \
    $(BUILD_DIR)/asm/JSystem/JASSimpleWaveBank.o                      \
    $(BUILD_DIR)/asm/JSystem/JASWaveArcLoader.o                       \
    $(BUILD_DIR)/asm/JSystem/JASWaveBank.o                            \
    $(BUILD_DIR)/asm/JSystem/JASWaveBankMgr.o                         \
    $(BUILD_DIR)/asm/JSystem/JASWSParser.o                            \
    $(BUILD_DIR)/asm/JSystem/JASAudioThread.o                         \
    $(BUILD_DIR)/asm/JSystem/JASChAllocQueue.o                        \
    $(BUILD_DIR)/asm/JSystem/JASChannel.o                             \
    $(BUILD_DIR)/asm/JSystem/JASChannelMgr.o                          \
    $(BUILD_DIR)/asm/JSystem/JASChGlobal.o                            \
    $(BUILD_DIR)/asm/JSystem/JASDriverIF.o                            \
    $(BUILD_DIR)/asm/JSystem/JASDriverTables.o                        \
    $(BUILD_DIR)/asm/JSystem/JASDSPBuf.o                              \
    $(BUILD_DIR)/asm/JSystem/JASDSPChannel.o                          \
    $(BUILD_DIR)/asm/JSystem/JASDSPInterface.o                        \
    $(BUILD_DIR)/asm/JSystem/JASOscillator.o                          \
    $(BUILD_DIR)/asm/JSystem/JASAiCtrl.o                              \
    $(BUILD_DIR)/asm/JSystem/JASCalc.o                                \
    $(BUILD_DIR)/asm/JSystem/JASCallback.o                            \
    $(BUILD_DIR)/asm/JSystem/JASCmdStack.o                            \
    $(BUILD_DIR)/asm/JSystem/JASDvdThread.o                           \
    $(BUILD_DIR)/asm/JSystem/JASHardStream.o                          \
    $(BUILD_DIR)/asm/JSystem/JASHeapCtrl.o                            \
    $(BUILD_DIR)/asm/JSystem/JASKernelDebug.o                         \
    $(BUILD_DIR)/asm/JSystem/JASProbe.o                               \
    $(BUILD_DIR)/asm/JSystem/JASRate.o                                \
    $(BUILD_DIR)/asm/JSystem/JASSystemHeap.o                          \
    $(BUILD_DIR)/asm/JSystem/JASVload.o                               \
    $(BUILD_DIR)/asm/JSystem/JASNoteMgr.o                             \
    $(BUILD_DIR)/asm/JSystem/JASOuterParam.o                          \
    $(BUILD_DIR)/asm/JSystem/JASPlayer_impl.o                         \
    $(BUILD_DIR)/asm/JSystem/JASRegisterParam.o                       \
    $(BUILD_DIR)/asm/JSystem/JASSeqCtrl.o                             \
    $(BUILD_DIR)/asm/JSystem/JASTrack.o                               \
    $(BUILD_DIR)/asm/JSystem/JASTrackInterrupt.o                      \
    $(BUILD_DIR)/asm/JSystem/JASTrackMgr.o                            \
    $(BUILD_DIR)/asm/JSystem/JASTrackPort.o                           \
    $(BUILD_DIR)/asm/JSystem/random.o                                 \
    $(BUILD_DIR)/asm/JSystem/J3DMaterialFactory_v21.o                 \
    $(BUILD_DIR)/asm/JSystem/JASSeqParser.o                           \
    $(BUILD_DIR)/asm/JSystem/J3DMaterialAttach.o                      \
    $(BUILD_DIR)/asm/JSystem/JPAEmitter.o                             \
    $(BUILD_DIR)/asm/JSystem/JPAEmitterManager.o                      \
    $(BUILD_DIR)/asm/JSystem/JPAField.o                               \
    $(BUILD_DIR)/asm/JSystem/JPAMath.o                                \
    $(BUILD_DIR)/asm/JSystem/JPAParticle.o                            \
    $(BUILD_DIR)/asm/JSystem/JPADrawSetupTev.o                        \
    $(BUILD_DIR)/asm/JSystem/JPADraw.o                                \
    $(BUILD_DIR)/asm/JSystem/JPADrawVisitor.o                         \
    $(BUILD_DIR)/asm/JSystem/JPAExTexShape.o                          \
    $(BUILD_DIR)/asm/JSystem/JPADataBlock.o                           \
    $(BUILD_DIR)/asm/JSystem/JPAEmitterLoader.o                       \
    $(BUILD_DIR)/asm/JSystem/JPABaseShape.o                           \
    $(BUILD_DIR)/asm/JSystem/JPAExtraShape.o                          \
    $(BUILD_DIR)/asm/JSystem/JPAResourceManager.o                     \
    $(BUILD_DIR)/asm/JSystem/JPASweepShape.o                          \
    $(BUILD_DIR)/asm/JSystem/JPATexture.o                             \
    $(BUILD_DIR)/asm/JSystem/JSGAmbientLight.o                        \
    $(BUILD_DIR)/asm/JSystem/JSGCamera.o                              \
    $(BUILD_DIR)/asm/JSystem/JSGActor.o                               \
    $(BUILD_DIR)/asm/JSystem/JSGLight.o                               \
    $(BUILD_DIR)/asm/JSystem/JSGObject.o                              \
    $(BUILD_DIR)/asm/JSystem/JSGSystem.o                              \
    $(BUILD_DIR)/asm/JSystem/dspproc.o                                \
    $(BUILD_DIR)/asm/JSystem/dsptask.o                                \
    $(BUILD_DIR)/asm/JSystem/osdsp.o                                  \
    $(BUILD_DIR)/asm/JSystem/osdsp_task.o                             \
    $(BUILD_DIR)/asm/Runtime.PPCEABI.H/__va_arg.o                     \
    $(BUILD_DIR)/asm/Runtime.PPCEABI.H/global_destructor_chain.o      \
    $(BUILD_DIR)/asm/Runtime.PPCEABI.H/NMWException.o                 \
    $(BUILD_DIR)/asm/Runtime.PPCEABI.H/ptmf.o                         \
    $(BUILD_DIR)/asm/Runtime.PPCEABI.H/ExceptionPPC.o                 \
    $(BUILD_DIR)/asm/Runtime.PPCEABI.H/runtime.o                      \
    $(BUILD_DIR)/asm/Runtime.PPCEABI.H/__init_cpp_exceptions.o        \
    $(BUILD_DIR)/asm/Runtime.PPCEABI.H/__mem.o                        \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/abort_exit.o                \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/ansi_files.o                \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/ansi_fp.o                   \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/buffer_io.o                 \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/critical_regions.ppc_eabi.o \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/ctype.o                     \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/direct_io.o                 \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/errno.o                     \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/mbstring.o                  \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/mem.o                       \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/mem_funcs.o                 \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/misc_io.o                   \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/printf.o                    \
    $(BUILD_DIR)/src/MSL_C.PPCEABI.bare.H/rand.o                      \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/scanf.o                     \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/string.o                    \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/strtoul.o                   \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/uart_console_io.o           \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/wchar_io.o                  \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/e_asin.o                    \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/e_atan2.o                   \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/s_atan.o                    \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/s_frexp.o                   \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/w_atan2.o                   \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/float.o                     \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/hyperbolicsf.o              \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/inverse_trig.o              \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/trigf.o                     \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/common_float_tables.o       \
    $(BUILD_DIR)/asm/MSL_C.PPCEABI.bare.H/exponentialsf.o             \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/mainloop.o                    \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/nubevent.o                    \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/nubinit.o                     \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/msg.o                         \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/msgbuf.o                      \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/serpoll.o                     \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/usr_put.o                     \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/dispatch.o                    \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/msghndlr.o                    \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/support.o                     \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/mutex_TRK.o                   \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/notify.o                      \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/flush_cache.o                 \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/mem_TRK.o                     \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/targimpl.o                    \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/__exception.o                 \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/dolphin_trk.o                 \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/mpc_7xx_603e.o                \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/main_TRK.o                    \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/dolphin_trk_glue.o            \
    $(BUILD_DIR)/asm/TRK_MINNOW_DOLPHIN/targcont.o                    \
    $(BUILD_DIR)/asm/base/PPCArch.o                                   \
    $(BUILD_DIR)/asm/db/db.o                                          \
    $(BUILD_DIR)/asm/os/OS.o                                          \
    $(BUILD_DIR)/asm/os/OSAlarm.o                                     \
    $(BUILD_DIR)/asm/os/OSAlloc.o                                     \
    $(BUILD_DIR)/asm/os/OSArena.o                                     \
    $(BUILD_DIR)/asm/os/OSAudioSystem.o                               \
    $(BUILD_DIR)/asm/os/OSCache.o                                     \
    $(BUILD_DIR)/asm/os/OSContext.o                                   \
    $(BUILD_DIR)/asm/os/OSError.o                                     \
    $(BUILD_DIR)/asm/os/OSFont.o                                      \
    $(BUILD_DIR)/asm/os/OSInterrupt.o                                 \
    $(BUILD_DIR)/asm/os/OSLink.o                                      \
    $(BUILD_DIR)/asm/os/OSMessage.o                                   \
    $(BUILD_DIR)/asm/os/OSMemory.o                                    \
    $(BUILD_DIR)/asm/os/OSMutex.o                                     \
    $(BUILD_DIR)/asm/os/OSReboot.o                                    \
    $(BUILD_DIR)/asm/os/OSReset.o                                     \
    $(BUILD_DIR)/asm/os/OSResetSW.o                                   \
    $(BUILD_DIR)/asm/os/OSRtc.o                                       \
    $(BUILD_DIR)/asm/os/OSStopwatch.o                                 \
    $(BUILD_DIR)/asm/os/OSSync.o                                      \
    $(BUILD_DIR)/asm/os/OSThread.o                                    \
    $(BUILD_DIR)/asm/os/OSTime.o                                      \
    $(BUILD_DIR)/asm/os/__start.o                                     \
    $(BUILD_DIR)/asm/os/__ppc_eabi_init.o                             \
    $(BUILD_DIR)/asm/mtx/mtx.o                                        \
    $(BUILD_DIR)/asm/mtx/mtxvec.o                                     \
    $(BUILD_DIR)/asm/mtx/mtx44.o                                      \
    $(BUILD_DIR)/asm/mtx/vec.o                                        \
    $(BUILD_DIR)/asm/dvd/dvdlow.o                                     \
    $(BUILD_DIR)/asm/dvd/dvdfs.o                                      \
    $(BUILD_DIR)/asm/dvd/dvd.o                                        \
    $(BUILD_DIR)/asm/dvd/dvdqueue.o                                   \
    $(BUILD_DIR)/asm/dvd/dvderror.o                                   \
    $(BUILD_DIR)/asm/dvd/fstload.o                                    \
    $(BUILD_DIR)/asm/vi/vi.o                                          \
    $(BUILD_DIR)/asm/pad/Padclamp.o                                   \
    $(BUILD_DIR)/asm/pad/Pad.o                                        \
    $(BUILD_DIR)/asm/ai/ai.o                                          \
    $(BUILD_DIR)/asm/ar/ar.o                                          \
    $(BUILD_DIR)/asm/ar/arq.o                                         \
    $(BUILD_DIR)/asm/dsp/dsp.o                                        \
    $(BUILD_DIR)/asm/dsp/dsp_debug.o                                  \
    $(BUILD_DIR)/asm/dsp/dsp_task.o                                   \
    $(BUILD_DIR)/asm/card/CARDBios.o                                  \
    $(BUILD_DIR)/asm/card/CARDUnlock.o                                \
    $(BUILD_DIR)/asm/card/CARDRdwr.o                                  \
    $(BUILD_DIR)/asm/card/CARDBlock.o                                 \
    $(BUILD_DIR)/asm/card/CARDDir.o                                   \
    $(BUILD_DIR)/asm/card/CARDCheck.o                                 \
    $(BUILD_DIR)/asm/card/CARDMount.o                                 \
    $(BUILD_DIR)/asm/card/CARDFormat.o                                \
    $(BUILD_DIR)/asm/card/CARDOpen.o                                  \
    $(BUILD_DIR)/asm/card/CARDCreate.o                                \
    $(BUILD_DIR)/asm/card/CARDRead.o                                  \
    $(BUILD_DIR)/asm/card/CARDWrite.o                                 \
    $(BUILD_DIR)/asm/card/CARDStat.o                                  \
    $(BUILD_DIR)/asm/card/CARDNet.o                                   \
    $(BUILD_DIR)/asm/gx/GXInit.o                                      \
    $(BUILD_DIR)/asm/gx/GXFifo.o                                      \
    $(BUILD_DIR)/asm/gx/GXAttr.o                                      \
    $(BUILD_DIR)/asm/gx/GXMisc.o                                      \
    $(BUILD_DIR)/asm/gx/GXGeometry.o                                  \
    $(BUILD_DIR)/asm/gx/GXFrameBuf.o                                  \
    $(BUILD_DIR)/asm/gx/GXLight.o                                     \
    $(BUILD_DIR)/asm/gx/GXTexture.o                                   \
    $(BUILD_DIR)/asm/gx/GXBump.o                                      \
    $(BUILD_DIR)/asm/gx/GXTev.o                                       \
    $(BUILD_DIR)/asm/gx/GXPixel.o                                     \
    $(BUILD_DIR)/asm/gx/GXDraw.o                                      \
    $(BUILD_DIR)/asm/gx/GXStubs.o                                     \
    $(BUILD_DIR)/asm/gx/GXDisplayList.o                               \
    $(BUILD_DIR)/asm/gx/GXTransform.o                                 \
    $(BUILD_DIR)/asm/gx/GXPerf.o                                      \
    $(BUILD_DIR)/asm/OdemuExi2/DebuggerDriver.o                       \
    $(BUILD_DIR)/asm/amcstubs/AmcExi2Stubs.o                          \
    $(BUILD_DIR)/asm/odenotstub/odenotstub.o                          \
    $(BUILD_DIR)/asm/gd/GDBase.o                                      \
    $(BUILD_DIR)/asm/gd/GDGeometry.o                                  \
    $(BUILD_DIR)/asm/gd/GDLight.o                                     \
    $(BUILD_DIR)/asm/gd/GDPixel.o                                     \
    $(BUILD_DIR)/asm/gd/GDTev.o                                       \
    $(BUILD_DIR)/asm/gd/GDTransform.o                                 \
    $(BUILD_DIR)/asm/si/SIBios.o                                      \
    $(BUILD_DIR)/asm/si/SISamplingRate.o                              \
    $(BUILD_DIR)/asm/exi/EXIBios.o                                    \
    $(BUILD_DIR)/asm/exi/EXIUart.o                                    \
    $(BUILD_DIR)/asm/thp/THPDec.o                                     \
    $(BUILD_DIR)/asm/thp/THPAudio.o                                   \
    $(BUILD_DIR)/asm/THPPlayer/THPAudioDecode.o                       \
    $(BUILD_DIR)/asm/THPPlayer/THPDraw.o                              \
    $(BUILD_DIR)/asm/THPPlayer/THPPlayer.o                            \
    $(BUILD_DIR)/asm/THPPlayer/THPRead.o                              \
    $(BUILD_DIR)/asm/THPPlayer/THPVideoDecode.o                       \
    $(BUILD_DIR)/asm/MarioUtil/DLUtil.o                               \
    $(BUILD_DIR)/asm/MarioUtil/DrawUtil.o                             \
    $(BUILD_DIR)/asm/MarioUtil/LightUtil.o                            \
    $(BUILD_DIR)/asm/MarioUtil/MathUtil.o                             \
    $(BUILD_DIR)/asm/MarioUtil/MtxUtil.o                              \
    $(BUILD_DIR)/asm/MarioUtil/ScreenUtil.o                           \
    $(BUILD_DIR)/asm/MarioUtil/ShadowUtil.o                           \
    $(BUILD_DIR)/asm/MarioUtil/gd-reinit-gx.o                         \
    $(BUILD_DIR)/asm/MarioUtil/EffectUtil.o                           \
    $(BUILD_DIR)/asm/MarioUtil/ModelUtil.o                            \
    $(BUILD_DIR)/asm/MarioUtil/RumbleMgr.o                            \
    $(BUILD_DIR)/asm/MarioUtil/RumbleData.o                           \
    $(BUILD_DIR)/src/MarioUtil/RumbleType.o                           \
    $(BUILD_DIR)/asm/MarioUtil/PacketUtil.o                           \
    $(BUILD_DIR)/asm/MarioUtil/GDUtil.o                               \
    $(BUILD_DIR)/asm/MarioUtil/TexUtil.o                              \
    $(BUILD_DIR)/src/MarioUtil/MapUtil.o                              \
    $(BUILD_DIR)/asm/MarioUtil/ToolData.o                             \
    $(BUILD_DIR)/asm/M3DUtil/M3UJoint.o                               \
    $(BUILD_DIR)/asm/M3DUtil/M3UModel.o                               \
    $(BUILD_DIR)/asm/M3DUtil/MActor.o                                 \
    $(BUILD_DIR)/asm/M3DUtil/MActorAnm.o                              \
    $(BUILD_DIR)/asm/M3DUtil/MActorData.o                             \
    $(BUILD_DIR)/asm/M3DUtil/SDLModel.o                               \
    $(BUILD_DIR)/asm/M3DUtil/MActorUtil.o                             \
    $(BUILD_DIR)/asm/M3DUtil/SampleCtrlNode.o                         \
    $(BUILD_DIR)/asm/M3DUtil/SampleCtrlModel.o                        \
    $(BUILD_DIR)/asm/M3DUtil/MotionBlendCtrl.o                        \
    $(BUILD_DIR)/asm/M3DUtil/LodAnm.o                                 \
    $(BUILD_DIR)/asm/System/BaseParam.o                               \
    $(BUILD_DIR)/asm/System/EmitterViewObj.o                          \
    $(BUILD_DIR)/asm/System/EventWatcher.o                            \
    $(BUILD_DIR)/src/System/FlagManager.o                             \
    $(BUILD_DIR)/asm/System/GCLogoDir.o                               \
    $(BUILD_DIR)/asm/System/J3DSysFlag.o                              \
    $(BUILD_DIR)/asm/System/MarDirector.o                             \
    $(BUILD_DIR)/asm/System/MarDirectorDirect.o                       \
    $(BUILD_DIR)/asm/System/MarDirectorEvent.o                        \
    $(BUILD_DIR)/asm/System/MarDirectorInitECT.o                      \
    $(BUILD_DIR)/asm/System/MarDirectorPreEntry.o                     \
    $(BUILD_DIR)/asm/System/MarDirectorSetup2.o                       \
    $(BUILD_DIR)/asm/System/marerr.o                                  \
    $(BUILD_DIR)/asm/System/MarNameRefGen.o                           \
    $(BUILD_DIR)/asm/System/MenuDir.o                                 \
    $(BUILD_DIR)/asm/System/Params.o                                  \
    $(BUILD_DIR)/src/System/ParamInst.o                               \
    $(BUILD_DIR)/asm/System/PerformList.o                             \
    $(BUILD_DIR)/asm/System/RenderModeObj.o                           \
    $(BUILD_DIR)/asm/System/SnapTimeObj.o                             \
    $(BUILD_DIR)/asm/System/TalkCursor.o                              \
    $(BUILD_DIR)/src/System/TexCache.o                                \
    $(BUILD_DIR)/asm/System/ZBufferCatch.o                            \
    $(BUILD_DIR)/asm/System/Application.o                             \
    $(BUILD_DIR)/asm/System/ScenarioArchiveName.o                     \
    $(BUILD_DIR)/asm/System/MarioGamePad.o                            \
    $(BUILD_DIR)/asm/System/StageEventInfo.o                          \
    $(BUILD_DIR)/src/System/StageUtil.o                               \
    $(BUILD_DIR)/src/System/Resolution.o                              \
    $(BUILD_DIR)/asm/System/PositionHolder.o                          \
    $(BUILD_DIR)/src/System/ProcessMeter.o                            \
    $(BUILD_DIR)/asm/System/TimeRec.o                                 \
    $(BUILD_DIR)/asm/System/DrawSyncManager.o                         \
    $(BUILD_DIR)/asm/System/THPRender.o                               \
    $(BUILD_DIR)/asm/System/MarNameRefGen_BossEnemy.o                 \
    $(BUILD_DIR)/asm/System/MarNameRefGen_Enemy.o                     \
    $(BUILD_DIR)/asm/System/MarNameRefGen_Map.o                       \
    $(BUILD_DIR)/asm/System/MarNameRefGen_MapObj.o                    \
    $(BUILD_DIR)/asm/System/MarNameRefGen_NPC.o                       \
    $(BUILD_DIR)/asm/System/CardManager.o                             \
    $(BUILD_DIR)/asm/System/MarDirectorLoadResource.o                 \
    $(BUILD_DIR)/asm/System/MovieDirector.o                           \
    $(BUILD_DIR)/asm/System/MarDirectorCreateObjects.o                \
    $(BUILD_DIR)/asm/System/MarDirectorSetupObjects.o                 \
    $(BUILD_DIR)/asm/System/MSoundMainSide.o                          \
    $(BUILD_DIR)/asm/System/TargetArrow.o                             \
    $(BUILD_DIR)/asm/Strategic/liveactor.o                            \
    $(BUILD_DIR)/asm/Strategic/liveinterp.o                           \
    $(BUILD_DIR)/asm/Strategic/livemanager.o                          \
    $(BUILD_DIR)/asm/Strategic/ObjHitCheck.o                          \
    $(BUILD_DIR)/asm/Strategic/objmanager.o                           \
    $(BUILD_DIR)/asm/Strategic/ObjModel.o                             \
    $(BUILD_DIR)/asm/Strategic/spcinterp.o                            \
    $(BUILD_DIR)/asm/Strategic/Strategy.o                             \
    $(BUILD_DIR)/asm/Strategic/question.o                             \
    $(BUILD_DIR)/asm/Strategic/smplcharacter.o                        \
    $(BUILD_DIR)/asm/Strategic/HitActor.o                             \
    $(BUILD_DIR)/asm/Strategic/binder.o                               \
    $(BUILD_DIR)/asm/Strategic/SharedParts.o                          \
    $(BUILD_DIR)/asm/Strategic/MirrorActor.o                          \
    $(BUILD_DIR)/asm/Player/Atom.o                                    \
    $(BUILD_DIR)/asm/Player/MarioAction.o                             \
    $(BUILD_DIR)/asm/Player/MarioAutodemo.o                           \
    $(BUILD_DIR)/asm/Player/MarioBlend.o                              \
    $(BUILD_DIR)/asm/Player/MarioCap.o                                \
    $(BUILD_DIR)/asm/Player/MarioCollision.o                          \
    $(BUILD_DIR)/asm/Player/MarioDraw.o                               \
    $(BUILD_DIR)/asm/Player/MarioJump.o                               \
    $(BUILD_DIR)/asm/Player/MarioMain.o                               \
    $(BUILD_DIR)/asm/Player/MarioMove.o                               \
    $(BUILD_DIR)/asm/Player/MarioPhysics.o                            \
    $(BUILD_DIR)/asm/Player/MarioRecord.o                             \
    $(BUILD_DIR)/asm/Player/MarioRun.o                                \
    $(BUILD_DIR)/asm/Player/MarioSpecial.o                            \
    $(BUILD_DIR)/asm/Player/MarioUpper.o                              \
    $(BUILD_DIR)/asm/Player/MarioParticle.o                           \
    $(BUILD_DIR)/asm/Player/MarioWait.o                               \
    $(BUILD_DIR)/asm/Player/SplashManager.o                           \
    $(BUILD_DIR)/asm/Player/Tongue.o                                  \
    $(BUILD_DIR)/asm/Player/WaterGun.o                                \
    $(BUILD_DIR)/asm/Player/Yoshi.o                                   \
    $(BUILD_DIR)/asm/Player/MarioEffect.o                             \
    $(BUILD_DIR)/asm/Player/MarioSwim.o                               \
    $(BUILD_DIR)/src/Player/MarioAccess.o                             \
    $(BUILD_DIR)/asm/Player/MarioInit.o                               \
    $(BUILD_DIR)/asm/Player/ModelWaterManager.o                       \
    $(BUILD_DIR)/asm/Player/MarioPositionObj.o                        \
    $(BUILD_DIR)/asm/Player/MarioCheckCol.o                           \
    $(BUILD_DIR)/asm/Player/MarioReceiveMsg.o                         \
    $(BUILD_DIR)/asm/Player/MarioSound.o                              \
    $(BUILD_DIR)/asm/NPC/NpcAnm.o                                     \
    $(BUILD_DIR)/asm/NPC/NpcBase.o                                    \
    $(BUILD_DIR)/asm/NPC/NpcCallback.o                                \
    $(BUILD_DIR)/asm/NPC/NpcManager.o                                 \
    $(BUILD_DIR)/asm/NPC/NpcNerve.o                                   \
    $(BUILD_DIR)/asm/NPC/NpcSave.o                                    \
    $(BUILD_DIR)/asm/NPC/NpcEvent.o                                   \
    $(BUILD_DIR)/asm/NPC/NpcInitData.o                                \
    $(BUILD_DIR)/asm/NPC/NpcInitPrg.o                                 \
    $(BUILD_DIR)/asm/NPC/NpcInbetween.o                               \
    $(BUILD_DIR)/asm/NPC/NpcParts.o                                   \
    $(BUILD_DIR)/asm/NPC/NpcColor.o                                   \
    $(BUILD_DIR)/asm/NPC/NpcSound.o                                   \
    $(BUILD_DIR)/asm/NPC/NpcChange.o                                  \
    $(BUILD_DIR)/asm/NPC/NpcThrow.o                                   \
    $(BUILD_DIR)/asm/NPC/NpcTrample.o                                 \
    $(BUILD_DIR)/asm/NPC/NpcEffect.o                                  \
    $(BUILD_DIR)/asm/NPC/NpcInitAnmData.o                             \
    $(BUILD_DIR)/src/NPC/NpcInitActionData.o                          \
    $(BUILD_DIR)/asm/NPC/NpcCoin.o                                    \
    $(BUILD_DIR)/src/NPC/NpcBalloon.o                                 \
    $(BUILD_DIR)/asm/NPC/NpcWalkTurn.o                                \
    $(BUILD_DIR)/asm/NPC/NpcCollision.o                               \
    $(BUILD_DIR)/asm/MSound/MAnmSound.o                               \
    $(BUILD_DIR)/asm/MSound/MSound.o                                  \
    $(BUILD_DIR)/asm/MSound/MSoundBGM.o                               \
    $(BUILD_DIR)/asm/MSound/MSoundDebug.o                             \
    $(BUILD_DIR)/asm/MSound/MSoundScene.o                             \
    $(BUILD_DIR)/asm/MSound/MSoundSE.o                                \
    $(BUILD_DIR)/asm/MSound/MSoundStruct.o                            \
    $(BUILD_DIR)/asm/MSound/MSHandle.o                                \
    $(BUILD_DIR)/asm/MSound/MSModBgm.o                                \
    $(BUILD_DIR)/asm/MoveBG/WoodBarrel.o                              \
    $(BUILD_DIR)/asm/MoveBG/MapObjBase.o                              \
    $(BUILD_DIR)/asm/MoveBG/MapObjInit.o                              \
    $(BUILD_DIR)/asm/MoveBG/MapObjGeneral.o                           \
    $(BUILD_DIR)/asm/MoveBG/MapObjManager.o                           \
    $(BUILD_DIR)/asm/MoveBG/MapObjLib.o                               \
    $(BUILD_DIR)/asm/MoveBG/Item.o                                    \
    $(BUILD_DIR)/asm/MoveBG/ItemManager.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjTown.o                              \
    $(BUILD_DIR)/asm/MoveBG/MapObjBlock.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjBianco.o                            \
    $(BUILD_DIR)/asm/MoveBG/MapObjSirena.o                            \
    $(BUILD_DIR)/asm/MoveBG/MapObjRicco.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjMamma.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjPinna.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjSample.o                            \
    $(BUILD_DIR)/asm/MoveBG/MapObjMare.o                              \
    $(BUILD_DIR)/asm/MoveBG/MapObjFlag.o                              \
    $(BUILD_DIR)/asm/MoveBG/MapObjWave.o                              \
    $(BUILD_DIR)/asm/MoveBG/MapObjFloat.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjPlane.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjCloud.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjBall.o                              \
    $(BUILD_DIR)/asm/MoveBG/MapObjAirport.o                           \
    $(BUILD_DIR)/asm/MoveBG/MapObjDolpic.o                            \
    $(BUILD_DIR)/asm/MoveBG/MapObjPollution.o                         \
    $(BUILD_DIR)/asm/MoveBG/MapObjGrass.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjPole.o                              \
    $(BUILD_DIR)/asm/MoveBG/MapObjWater.o                             \
    $(BUILD_DIR)/asm/MoveBG/ModelGate.o                               \
    $(BUILD_DIR)/asm/MoveBG/MapObjFence.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjOption.o                            \
    $(BUILD_DIR)/asm/MoveBG/MapObjRailBlock.o                         \
    $(BUILD_DIR)/asm/MoveBG/MapObjMonte.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjTree.o                              \
    $(BUILD_DIR)/asm/MoveBG/MapObjTumblePole.o                        \
    $(BUILD_DIR)/asm/MoveBG/MapObjEx.o                                \
    $(BUILD_DIR)/asm/MoveBG/Pool.o                                    \
    $(BUILD_DIR)/asm/MoveBG/MapObjCorona.o                            \
    $(BUILD_DIR)/asm/MoveBG/MapObjItem2.o                             \
    $(BUILD_DIR)/asm/MoveBG/MapObjHide.o                              \
    $(BUILD_DIR)/asm/MoveBG/MapObjTrap.o                              \
    $(BUILD_DIR)/asm/Map/JointModel.o                                 \
    $(BUILD_DIR)/asm/Map/JointModelManager.o                          \
    $(BUILD_DIR)/asm/Map/JointObj.o                                   \
    $(BUILD_DIR)/asm/Map/Map.o                                        \
    $(BUILD_DIR)/asm/Map/MapArea.o                                    \
    $(BUILD_DIR)/asm/Map/MapCheck.o                                   \
    $(BUILD_DIR)/asm/Map/MapCollisionData.o                           \
    $(BUILD_DIR)/asm/Map/MapCollisionEntry.o                          \
    $(BUILD_DIR)/asm/Map/MapCollisionManager.o                        \
    $(BUILD_DIR)/asm/Map/MapDraw.o                                    \
    $(BUILD_DIR)/asm/Map/MapEvent.o                                   \
    $(BUILD_DIR)/asm/Map/MapEventSink.o                               \
    $(BUILD_DIR)/asm/Map/MapMakeData.o                                \
    $(BUILD_DIR)/asm/Map/MapMakeList.o                                \
    $(BUILD_DIR)/asm/Map/MapMirror.o                                  \
    $(BUILD_DIR)/asm/Map/MapModel.o                                   \
    $(BUILD_DIR)/asm/Map/MapWarp.o                                    \
    $(BUILD_DIR)/asm/Map/MapStaticObject.o                            \
    $(BUILD_DIR)/asm/Map/MapWire.o                                    \
    $(BUILD_DIR)/asm/Map/MapWireManager.o                             \
    $(BUILD_DIR)/asm/Map/MapXlu.o                                     \
    $(BUILD_DIR)/asm/Map/PollutionAction.o                            \
    $(BUILD_DIR)/asm/Map/PollutionCount.o                             \
    $(BUILD_DIR)/asm/Map/PollutionManager.o                           \
    $(BUILD_DIR)/asm/Map/PollutionObj.o                               \
    $(BUILD_DIR)/asm/Map/PollutionPos.o                               \
    $(BUILD_DIR)/asm/Map/Shimmer.o                                    \
    $(BUILD_DIR)/asm/Map/Sky.o                                        \
    $(BUILD_DIR)/asm/Map/MapEventSirena.o                             \
    $(BUILD_DIR)/asm/Map/PollutionLayer.o                             \
    $(BUILD_DIR)/asm/Map/PollutionEvent.o                             \
    $(BUILD_DIR)/asm/Map/MapCollisionPlane.o                          \
    $(BUILD_DIR)/asm/Map/MarineSnow.o                                 \
    $(BUILD_DIR)/asm/Map/MapData.o                                    \
    $(BUILD_DIR)/asm/Map/MapEventDolpic.o                             \
    $(BUILD_DIR)/asm/Map/MapEventMare.o                               \
    $(BUILD_DIR)/asm/Map/BathWaterManager.o                           \
    $(BUILD_DIR)/asm/Map/StickyStainManager.o                         \
    $(BUILD_DIR)/asm/GC2D/ChangeValue.o                               \
    $(BUILD_DIR)/asm/GC2D/Coord2D.o                                   \
    $(BUILD_DIR)/asm/GC2D/ExPane.o                                    \
    $(BUILD_DIR)/asm/GC2D/Menu.o                                      \
    $(BUILD_DIR)/asm/GC2D/ScrnFader.o                                 \
    $(BUILD_DIR)/asm/GC2D/GCConsole2.o                                \
    $(BUILD_DIR)/asm/GC2D/Talk2D2.o                                   \
    $(BUILD_DIR)/asm/GC2D/BoundPane.o                                 \
    $(BUILD_DIR)/asm/GC2D/PauseMenu2.o                                \
    $(BUILD_DIR)/asm/GC2D/MessageLoader.o                             \
    $(BUILD_DIR)/asm/GC2D/HelpActor.o                                 \
    $(BUILD_DIR)/asm/GC2D/MessageUtil.o                               \
    $(BUILD_DIR)/asm/GC2D/CardSave.o                                  \
    $(BUILD_DIR)/asm/GC2D/CardLoad.o                                  \
    $(BUILD_DIR)/asm/GC2D/ConsoleStr.o                                \
    $(BUILD_DIR)/asm/GC2D/SelectMenu.o                                \
    $(BUILD_DIR)/asm/GC2D/SelectDir.o                                 \
    $(BUILD_DIR)/asm/GC2D/SelectShine2.o                              \
    $(BUILD_DIR)/asm/GC2D/BlendPane.o                                 \
    $(BUILD_DIR)/asm/GC2D/Guide.o                                     \
    $(BUILD_DIR)/asm/GC2D/SunGlass.o                                  \
    $(BUILD_DIR)/asm/GC2D/ShineFader.o                                \
    $(BUILD_DIR)/asm/GC2D/ProgSelect.o                                \
    $(BUILD_DIR)/asm/GC2D/hx_wiper.o                                  \
    $(BUILD_DIR)/asm/GC2D/MovieSubtitle.o                             \
    $(BUILD_DIR)/asm/GC2D/Option.o                                    \
    $(BUILD_DIR)/asm/GC2D/MovieRumble.o                               \
    $(BUILD_DIR)/asm/Enemy/conductor.o                                \
    $(BUILD_DIR)/asm/Enemy/effectObj.o                                \
    $(BUILD_DIR)/asm/Enemy/emario.o                                   \
    $(BUILD_DIR)/asm/Enemy/enemy.o                                    \
    $(BUILD_DIR)/asm/Enemy/enemyAttachment.o                          \
    $(BUILD_DIR)/asm/Enemy/enemymanager.o                             \
    $(BUILD_DIR)/asm/Enemy/enemyMario.o                               \
    $(BUILD_DIR)/asm/Enemy/feetinv.o                                  \
    $(BUILD_DIR)/asm/Enemy/gesso.o                                    \
    $(BUILD_DIR)/asm/Enemy/graph.o                                    \
    $(BUILD_DIR)/asm/Enemy/hamukuri.o                                 \
    $(BUILD_DIR)/asm/Enemy/hinokuri2.o                                \
    $(BUILD_DIR)/asm/Enemy/mameGesso.o                                \
    $(BUILD_DIR)/asm/Enemy/namekuri.o                                 \
    $(BUILD_DIR)/asm/Enemy/pakkun.o                                   \
    $(BUILD_DIR)/asm/Enemy/smallEnemy.o                               \
    $(BUILD_DIR)/asm/Enemy/spider.o                                   \
    $(BUILD_DIR)/asm/Enemy/spline.o                                   \
    $(BUILD_DIR)/asm/Enemy/typicalenemy.o                             \
    $(BUILD_DIR)/asm/Enemy/walker.o                                   \
    $(BUILD_DIR)/asm/Enemy/walkerEnemy.o                              \
    $(BUILD_DIR)/asm/Enemy/bossgesso.o                                \
    $(BUILD_DIR)/asm/Enemy/elecNokonoko.o                             \
    $(BUILD_DIR)/asm/Enemy/telesa.o                                   \
    $(BUILD_DIR)/asm/Enemy/fireWanwan.o                               \
    $(BUILD_DIR)/asm/Enemy/enemytable.o                               \
    $(BUILD_DIR)/asm/Enemy/generator.o                                \
    $(BUILD_DIR)/asm/Enemy/bosspakkun.o                               \
    $(BUILD_DIR)/asm/Enemy/tobiPuku.o                                 \
    $(BUILD_DIR)/asm/Enemy/tinkoopa.o                                 \
    $(BUILD_DIR)/asm/Enemy/launcher.o                                 \
    $(BUILD_DIR)/asm/Enemy/bosswanwan.o                               \
    $(BUILD_DIR)/asm/Enemy/chuuhana.o                                 \
    $(BUILD_DIR)/asm/Enemy/igaiga.o                                   \
    $(BUILD_DIR)/asm/Enemy/poihana.o                                  \
    $(BUILD_DIR)/asm/Enemy/tamaNoko.o                                 \
    $(BUILD_DIR)/asm/Enemy/bosstelesa.o                               \
    $(BUILD_DIR)/asm/Enemy/riccohook.o                                \
    $(BUILD_DIR)/asm/Enemy/bombhei.o                                  \
    $(BUILD_DIR)/asm/Enemy/cannon.o                                   \
    $(BUILD_DIR)/asm/Enemy/bosseel.o                                  \
    $(BUILD_DIR)/asm/Enemy/killer.o                                   \
    $(BUILD_DIR)/asm/Enemy/beam.o                                     \
    $(BUILD_DIR)/asm/Enemy/hanasambo.o                                \
    $(BUILD_DIR)/asm/Enemy/popo.o                                     \
    $(BUILD_DIR)/asm/Enemy/SleepBossHanachan.o                        \
    $(BUILD_DIR)/asm/Enemy/DemoBossHanachanBase.o                     \
    $(BUILD_DIR)/asm/Enemy/fruitsboat.o                               \
    $(BUILD_DIR)/asm/Enemy/BossHanachanSub.o                          \
    $(BUILD_DIR)/asm/Enemy/BossHanachanMain.o                         \
    $(BUILD_DIR)/asm/Enemy/BossHanachanNerve.o                        \
    $(BUILD_DIR)/asm/Enemy/BossHanachanAnm.o                          \
    $(BUILD_DIR)/asm/Enemy/BossHanachanParts.o                        \
    $(BUILD_DIR)/asm/Enemy/BossHanachanSave.o                         \
    $(BUILD_DIR)/asm/Enemy/amiNoko.o                                  \
    $(BUILD_DIR)/asm/Enemy/gatekeeper.o                               \
    $(BUILD_DIR)/asm/Enemy/BossHanachanEffect.o                       \
    $(BUILD_DIR)/asm/Enemy/egggen.o                                   \
    $(BUILD_DIR)/asm/Enemy/seal.o                                     \
    $(BUILD_DIR)/asm/Enemy/bgpoldrop.o                                \
    $(BUILD_DIR)/asm/Enemy/bgtentacle.o                               \
    $(BUILD_DIR)/asm/Enemy/effectEnemy.o                              \
    $(BUILD_DIR)/asm/Enemy/hauntLeg.o                                 \
    $(BUILD_DIR)/asm/Enemy/areacylinder.o                             \
    $(BUILD_DIR)/asm/Enemy/wireTrap.o                                 \
    $(BUILD_DIR)/asm/Enemy/BossHanachanSound.o                        \
    $(BUILD_DIR)/asm/Enemy/rocket.o                                   \
    $(BUILD_DIR)/asm/Enemy/Kazekun.o                                  \
    $(BUILD_DIR)/asm/Enemy/bossManta.o                                \
    $(BUILD_DIR)/asm/Enemy/wireBinder.o                               \
    $(BUILD_DIR)/asm/Enemy/yunbo.o                                    \
    $(BUILD_DIR)/asm/Enemy/koopajr.o                                  \
    $(BUILD_DIR)/asm/Enemy/Kumokun.o                                  \
    $(BUILD_DIR)/asm/Enemy/Koopa.o                                    \
    $(BUILD_DIR)/asm/Enemy/Kukku.o                                    \
    $(BUILD_DIR)/asm/Enemy/Amenbo.o                                   \
    $(BUILD_DIR)/asm/Enemy/BathtubPeach.o                             \
    $(BUILD_DIR)/asm/Enemy/BathtubKiller.o                            \
    $(BUILD_DIR)/asm/Enemy/coasterkiller.o                            \
    $(BUILD_DIR)/asm/Enemy/DebuTelesa.o                               \
    $(BUILD_DIR)/asm/Enemy/TabePuku.o                                 \
    $(BUILD_DIR)/asm/Enemy/BathtubBinder.o                            \
    $(BUILD_DIR)/asm/Enemy/limitkoopa.o                               \
    $(BUILD_DIR)/asm/Enemy/limitkoopajr.o                             \
    $(BUILD_DIR)/asm/Camera/CameraBGCheck.o                           \
    $(BUILD_DIR)/asm/Camera/CameraChange.o                            \
    $(BUILD_DIR)/asm/Camera/CameraCodeControl.o                       \
    $(BUILD_DIR)/asm/Camera/cameragc.o                                \
    $(BUILD_DIR)/asm/Camera/CameraHeightPan.o                         \
    $(BUILD_DIR)/asm/Camera/CameraInbetween.o                         \
    $(BUILD_DIR)/asm/Camera/CameraKindParam.o                         \
    $(BUILD_DIR)/asm/Camera/cameralib.o                               \
    $(BUILD_DIR)/asm/Camera/CameraMarioData.o                         \
    $(BUILD_DIR)/asm/Camera/CameraNotice.o                            \
    $(BUILD_DIR)/asm/Camera/CameraNormal.o                            \
    $(BUILD_DIR)/asm/Camera/camerasave.o                              \
    $(BUILD_DIR)/asm/Camera/camerashake.o                             \
    $(BUILD_DIR)/asm/Camera/CameraTalk.o                              \
    $(BUILD_DIR)/asm/Camera/lensflare.o                               \
    $(BUILD_DIR)/asm/Camera/lensglow.o                                \
    $(BUILD_DIR)/asm/Camera/sunmgr.o                                  \
    $(BUILD_DIR)/asm/Camera/sunmodel.o                                \
    $(BUILD_DIR)/asm/Camera/CubeManagerBase.o                         \
    $(BUILD_DIR)/asm/Camera/CameraMapTool.o                           \
    $(BUILD_DIR)/asm/Camera/CubeMapTool.o                             \
    $(BUILD_DIR)/asm/Camera/CameraMultiPlayer.o                       \
    $(BUILD_DIR)/asm/Camera/CameraJetCoaster.o                        \
    $(BUILD_DIR)/asm/Camera/CameraBck.o                               \
    $(BUILD_DIR)/asm/Camera/CameraOption.o                            \
    $(BUILD_DIR)/asm/Camera/CameraDemo.o                              \
    $(BUILD_DIR)/asm/Camera/CameraWarp.o                              \
    $(BUILD_DIR)/asm/Camera/CameraMode.o                              \
    $(BUILD_DIR)/asm/Camera/CamShakeDefine.o                          \
    $(BUILD_DIR)/asm/Camera/CameraSecureView.o                        \
    $(BUILD_DIR)/asm/Animal/boid.o                                    \
    $(BUILD_DIR)/asm/Animal/fishoid.o                                 \
    $(BUILD_DIR)/asm/Animal/AnimalBase.o                              \
    $(BUILD_DIR)/asm/Animal/AnimalManager.o                           \
    $(BUILD_DIR)/asm/Animal/AnimalSave.o                              \
    $(BUILD_DIR)/asm/Animal/AnimalNerve.o                             \
    $(BUILD_DIR)/asm/Animal/Bird.o                                    \
    $(BUILD_DIR)/asm/Animal/BeeHive.o                                 \
    $(BUILD_DIR)/asm/Animal/Butterfly.o                               \
    $(BUILD_DIR)/asm/JSystem/bss_extras.o
