#include <Camera/camerasave.hpp>

static const char* dummyMactorStringValue1 = "\0\0\0\0\0\0\0\0\0\0\0";
static const char* SMS_NO_MEMORY_MESSAGE   = "メモリが足りません\n";

TCamSaveNotice::TCamSaveNotice()
    : TParams("/Camera/camera_bossA.prm")
    , PARAM_INIT(mOnDist, 2500.0f)
    , PARAM_INIT(mOffDist, 4000.0f)
    , PARAM_INIT(mOnClipRatio, 1.0f)
    , PARAM_INIT(mOffClipRatio, 3.0f)
    , PARAM_INIT(mOnDegree, 150.0f)
    , PARAM_INIT(mRotateYSpeed, 300)
    , PARAM_INIT(mRotateMinDistXZ, 20.0f)
    , PARAM_INIT(mRotateFastMinDistXZ, 500.0f)
    , PARAM_INIT(mRotateMagnifXmax, 1.0f)
{
	load(mPrmPath);
}

TCamSaveShake::TCamSaveShake(const char* path)
    : TParams(path)
    , PARAM_INIT(mShakeTime, 40)
    , PARAM_INIT(mShakeAmpX, 500.0f)
    , PARAM_INIT(mShakeVelX, 5000)
    , PARAM_INIT(mShakeAmpY, 0.0f)
    , PARAM_INIT(mShakeVelY, 0)
    , PARAM_INIT(mShakeAmpZ, 0.0f)
    , PARAM_INIT(mShakeVelZ, 0)
{
	load(mPrmPath);
}

TCamSaveJetCoaster::TCamSaveJetCoaster()
    : TParams("/Camera/camera_jetCoaster.prm")
    , PARAM_INIT(mSLOffsetAngleXLimit, 10000)
    , PARAM_INIT(mSLOffsetAngleYLimit, 10000)
    , PARAM_INIT(mSLOffsetAngleXManualSpeed, 250)
    , PARAM_INIT(mSLOffsetAngleYManualSpeed, 250)
    , PARAM_INIT(mSLOffsetAngleXChase, 25)
    , PARAM_INIT(mSLOffsetAngleYChase, 25)
{
	load(mPrmPath);
}

TCamSaveEx::TCamSaveEx()
    : TParams("/Camera/camera_normal.prm")
    , PARAM_INIT(mXRotStart, 0.2f)
    , PARAM_INIT(mPanAfterMagnif, 0.01f)
    , PARAM_INIT(mPanAfterMinHeight, 1.5f)
    , PARAM_INIT(mPanWarpAngleX, -10000)
    , PARAM_INIT(mSLMinCushionXZ, 300.0f)
    , PARAM_INIT(mSLWallCheckRadius, 80.0f)
    , PARAM_INIT(mSLWallRevisionRatio, 1.0f)
    , PARAM_INIT(mGroundChangeY, 20.0f)
    , PARAM_INIT(mSLGroundHeightNormal, 144.0f)
    , PARAM_INIT(mSLGroundHeightReadyGun, 30.0f)
    , PARAM_INIT(mSLRoofChangeY, 20.0f)
    , PARAM_INIT(mSLRoofHeight, 60.0f)
    , PARAM_INIT(mInHouseMinFrame, 24)
    , PARAM_INIT(mYButtonRotateChase, 2)
    , PARAM_INIT(mLButtonRotateChase, 10)
    , PARAM_INIT(mSLAddAngleYSpeed, 50)
    , PARAM_INIT(mSLReproduceDemoNearClip, 30.0f)
    , PARAM_INIT(mSLHoldAngleXChase, 50)
    , PARAM_INIT(mSLHoldDistChase, 0.02f)
    , PARAM_INIT(mSLAimAngleYChaseMin, 60)
    , PARAM_INIT(mSLAimAngleYChaseMax, 32767)
    , PARAM_INIT(mSLLimitMinAngleX, -15872)
    , PARAM_INIT(mSLLimitMaxAngleX, 15872)
    , PARAM_INIT(mSLSlopeMaxAngleX, 8192)
    , PARAM_INIT(mSLSlopeSpeedAngleX, 50)
    , PARAM_INIT(mSLSlopeForwardDistXZ, 50.0f)
{
	load(mPrmPath);
}

TCamSaveKindParam::TCamSaveKindParam(const char* path)
    : TParams(path)
    , PARAM_INIT(mSLFovy, 50.0f)
    , PARAM_INIT(mSLNearClip, 10.0f)
    , PARAM_INIT(mSLDistMin, 450.0f)
    , PARAM_INIT(mSLDistMax, 2000.0f)
    , PARAM_INIT(mSLCushionMin, 350.0f)
    , PARAM_INIT(mSLCushionMax, 600.0f)
    , PARAM_INIT(mSLXAngleMin, 0x37E)
    , PARAM_INIT(mSLXAngleMax, 10000)
    , PARAM_INIT(mSLXRotRatioManualSpeed, 0.01f)
    , PARAM_INIT(mSLYAngleManualSpeedXMin, 250)
    , PARAM_INIT(mSLYAngleManualSpeedXMax, 250)
    , PARAM_INIT(mSLAtOffsetY, 133.398f)
    , PARAM_INIT(mSLXRotRatioAtOffsetY, 0.0f)
    , PARAM_INIT(mSLTargetAtJumpOffsetY, -100.0f)
    , PARAM_INIT(mSLAtJumpOffsetSpeed, 20.0f)
    , PARAM_INIT(mSLHeightPanChaseRateY, 0.0f)
    , PARAM_INIT(mSLSecureViewChase, 0.01f)
    , PARAM_INIT(mSLSecureViewDistXMin, 0.0f)
    , PARAM_INIT(mSLSecureViewDistZMin, 0.0f)
    , PARAM_INIT(mSLSecureViewDistXMax, 0.0f)
    , PARAM_INIT(mSLSecureViewDistZMax, 0.0f)
    , PARAM_INIT(mSLHoldAddDistXZMin, 350.0f)
    , PARAM_INIT(mSLHoldAddDistXZMax, 0.0f)
    , PARAM_INIT(mSLHoldOffsetAngleXMin, 0)
    , PARAM_INIT(mSLHoldOffsetAngleXMax, 0)
    , PARAM_INIT(mSLOffsetAngleX, 0)
    , PARAM_INIT(mSLOffsetAngleY, 0)
    , PARAM_INIT(mSLOffsetLookatXZ, 0.0f)
    , PARAM_INIT(mSLMaxAddAngleY, 0)
    , PARAM_INIT(mSLAutoChaseStartFrame, 0)
    , PARAM_INIT(mSLAutoChaseCompleteFrame, 0)
    , PARAM_INIT(mSLFollowSpeedXmin, 3.5f)
    , PARAM_INIT(mSLFollowSpeedXmax, 1.0f)
    , PARAM_INIT(mSLJumpFollowSpeedXmin, 2.0f)
    , PARAM_INIT(mSLJumpFollowSpeedXmax, 0.0f)
    , PARAM_INIT(mSLObstructMaginfXmin, 1.5f)
    , PARAM_INIT(mSLObstructMaginfXmax, 1.2f)
    , PARAM_INIT(mSLInHouseMaginfXmin, 1.7f)
    , PARAM_INIT(mSLInHouseMaginfXmax, 1.3f)
    , PARAM_INIT(mSLLFollowMaginfXmin, 4.0f)
    , PARAM_INIT(mSLLFollowMaginfXmax, 1.5f)
    , PARAM_INIT(mSLPosChaseRateXZ, 0.04f)
    , PARAM_INIT(mSLPosChaseRateXZ_C, 0.3f)
    , PARAM_INIT(mSLPosChaseRateY, 0.08f)
    , PARAM_INIT(mSLPosChaseRateY_C, 0.3f)
    , PARAM_INIT(mSLAtChaseRateXZ, 0.1f)
    , PARAM_INIT(mSLAtChaseRateY, 0.03f)
    , PARAM_INIT(mSLInbetFollow, 16)
    , PARAM_INIT(mSLInbetParallel, 16)
    , PARAM_INIT(mSLInbetMultiPlayer, 16)
    , PARAM_INIT(mSLInbetWallJump, 16)
    , PARAM_INIT(mSLInbetHipAttack, 16)
    , PARAM_INIT(mSLInbetRocketJump, 16)
    , PARAM_INIT(mSLInbetWire, 16)
    , PARAM_INIT(mSLInbetLNormal, 16)
    , PARAM_INIT(mSLInbetMareUnderGround, 16)
    , PARAM_INIT(mSLInbetDefiniteD2, 16)
    , PARAM_INIT(mSLInbetTalkE, 16)
    , PARAM_INIT(mSLInbetLeanMirror, 16)
    , PARAM_INIT(mSLInbetTalkA, 16)
    , PARAM_INIT(mSLInbetUnderGround, 16)
    , PARAM_INIT(mSLInbetIndoor, 16)
    , PARAM_INIT(mSLInbetHang, 16)
    , PARAM_INIT(mSLInbetWireHang, 16)
    , PARAM_INIT(mSLInbetSandBird, 16)
    , PARAM_INIT(mSLInbetHovering, 16)
    , PARAM_INIT(mSLInbetJumpCode, 16)
    , PARAM_INIT(mSLInbetDelfino, 16)
    , PARAM_INIT(mSLInbetClimb, 16)
    , PARAM_INIT(mSLInbetFixA, 16)
    , PARAM_INIT(mSLInbetFixB, 16)
    , PARAM_INIT(mSLInbetFixC, 1)
    , PARAM_INIT(mSLInbetFixD, 1)
    , PARAM_INIT(mSLInbetFixE, 1)
    , PARAM_INIT(mSLInbetFixF, 1)
    , PARAM_INIT(mSLInbetFixG, 1)
    , PARAM_INIT(mSLInbetFixH, 1)
    , PARAM_INIT(mSLInbetDefiniteA, 16)
    , PARAM_INIT(mSLInbetDefiniteB, 16)
    , PARAM_INIT(mSLInbetDefiniteC, 1)
    , PARAM_INIT(mSLInbetDefiniteD, 1)
    , PARAM_INIT(mSLInbetDefiniteE, 1)
    , PARAM_INIT(mSLInbetDefiniteF, 1)
    , PARAM_INIT(mSLInbetDefiniteG, 1)
    , PARAM_INIT(mSLInbetDefiniteH, 1)
    , PARAM_INIT(mSLInbetExMap0, 16)
    , PARAM_INIT(mSLInbetTowerA, 16)
    , PARAM_INIT(mSLInbetTowerB, 16)
    , PARAM_INIT(mSLInbetTowerC, 16)
    , PARAM_INIT(mSLInbetSlider, 16)
    , PARAM_INIT(mSLInbetDiving, 16)
    , PARAM_INIT(mSLInbetTurbo, 16)
    , PARAM_INIT(mSLInbetTalkB, 16)
    , PARAM_INIT(mSLInbetJetCoaster, 16)
    , PARAM_INIT(mSLInbetParallelB, 16)
    , PARAM_INIT(mSLInbetSurfing, 16)
    , PARAM_INIT(mSLInbetSwimming, 16)
    , PARAM_INIT(mSLInbetClimbJump, 16)
    , PARAM_INIT(mSLInbetLookDown, 16)
    , PARAM_INIT(mSLInbetRailFence, 16)
    , PARAM_INIT(mSLInbetFollowB, 16)
    , PARAM_INIT(mSLInbetFollowC, 16)
    , PARAM_INIT(mSLInbetTowerD, 16)
    , PARAM_INIT(mSLInbetDelfinoAttic, 16)
    , PARAM_INIT(mSLInbetBossGeso, 16)
    , PARAM_INIT(mSLInbetFixI, 16)
    , PARAM_INIT(mSLInbetDefiniteI, 16)
    , PARAM_INIT(mSLInbetFence, 16)
    , PARAM_INIT(mSLInbetMonteFence, 16)
    , PARAM_INIT(mSLInbetMonteHang, 16)
    , PARAM_INIT(mSLInbetTalkC, 16)
    , PARAM_INIT(mSLInbetTalkD, 16)
    , PARAM_INIT(mSLInbetTowerE, 16)
    , PARAM_INIT(mSLInbetDelfinoB, 16)
    , PARAM_INIT(mSLInbetCancan, 16)
    , PARAM_INIT(mSLInbetAquaticTurbo, 16)
    , PARAM_INIT(mSLInbetFollowD, 16)
    , PARAM_INIT(mSLInbetFollowE, 16)
    , PARAM_INIT(mSLInbetParallelC, 16)
    , PARAM_INIT(mSLInbetParallelD, 16)
{
	load(mPrmPath);
}
