#include <Camera/CameraShake.hpp>

static const char* dummyMactorStringValue1 = "\0\0\0\0\0\0\0\0\0\0\0";
static const char* SMS_NO_MEMORY_MESSAGE   = "メモリが足りません\n";

const char* TCameraShake::mCamShakeNameSave[] = {
	"/Camera/shakeHipDrop.prm",
	"/Camera/shakeWallJump.prm",
	"/Camera/shakeDamage.prm",
	"/Camera/shakeEnemy.prm",
	"/Camera/shakeEnemy2.prm",
	"/Camera/shakeBuildingAppear.prm",
	"/Camera/shakeKiller.prm",
	"/Camera/shakeTamanoko.prm",
	"/Camera/shakeBohaSandCrash.prm",
	"/Camera/shakeBohaSlip.prm",
	"/Camera/shakeBohaStep.prm",
	"/Camera/shakeBohaRun.prm",
	"/Camera/shakeBohaGetup.prm",
	"/Camera/shakeSandBombAppear.prm",
	"/Camera/shakeBopaDown.prm",
	"/Camera/shakeBopaPopo.prm",
	"/Camera/shakeBopaGetup.prm",
	"/Camera/shakeBopaDownLoop.prm",
	"/Camera/shakeBogeBeakHit.prm",
	"/Camera/shakeBogeTumble.prm",
	"/Camera/shakeBogeLand.prm",
	"/Camera/shakeBogeTeHit.prm",
	"/Camera/shakeBowaLand1.prm",
	"/Camera/shakeBowaLand2.prm",
	"/Camera/shakeBEelRoll.prm",
	"/Camera/shakeBEelOut.prm",
	"/Camera/shakeBEelHanukeIn.prm",
	"/Camera/shakeBEelSuckOpen.prm",
	"/Camera/shakeBEelSuckLoop.prm",
	"/Camera/shakeBEelSuckClose.prm",
	"/Camera/shakeBEelDie.prm",
	"/Camera/shakeBTelesaDamage.prm",
	"/Camera/shakeBTelesaHit.prm",
	"/Camera/shakeBTelesaDown.prm",
	"/Camera/shakeBTelesaAppear.prm",
	"/Camera/shakeBTelesaRoll.prm",
	"/Camera/shakeCannonDemo.prm",
	"/Camera/shakeBathtubGripBreaking.prm",
	"/Camera/shakeBathtubGripBreaking2.prm",
	"/Camera/shakeKoopaHipdrop.prm",
	"/Camera/shakeBathtubKiller.prm",
};
