#include <Enemy/BossHanachanChangeSaveParams.hpp>

static const char* dummyMactorStringValue1 = "\0\0\0\0\0\0\0\0\0\0\0";
static const char* SMS_NO_MEMORY_MESSAGE   = "メモリが足りません\n";

TBossHanachanCommonSaveParams::TBossHanachanCommonSaveParams(const char* path)
    : TParams(path)
    , PARAM_INIT(mSLViewClipFar, 25000.0f)
    , PARAM_INIT(mSLViewClipRadius, 3500.0f)
    , PARAM_INIT(mSLHeadHitOffsetY, 400.0f)
    , PARAM_INIT(mSLHeadAttackRadius, 475.0f)
    , PARAM_INIT(mSLHeadAttackHeight, 840.0f)
    , PARAM_INIT(mSLHeadDamageRadius, 450.0f)
    , PARAM_INIT(mSLHeadDamageHeight, 500.0f)
    , PARAM_INIT(mSLBodyHitOffsetY, 200.0f)
    , PARAM_INIT(mSLBodyAttackRadius, 325.0f)
    , PARAM_INIT(mSLBodyAttackHeight, 515.0f)
    , PARAM_INIT(mSLBodyDamageRadius, 300.0f)
    , PARAM_INIT(mSLBodyDamageHeight, 300.0f)
    , PARAM_INIT(mSLFootHitOffsetY, 75.0f)
    , PARAM_INIT(mSLFootAttackRadius, 150.0f)
    , PARAM_INIT(mSLFootAttackHeight, 200.0f)
    , PARAM_INIT(mSLFootDamageRadius, 0.0f)
    , PARAM_INIT(mSLFootDamageHeight, 0.0f)
    , PARAM_INIT(mSLHeadLength, 470.0f)
    , PARAM_INIT(mSLBodyLength, 420.0f)
    , PARAM_INIT(mSLHeadShadowSize, 850.0f)
    , PARAM_INIT(mSLBodyShadowSize, 525.0f)
    , PARAM_INIT(mSLHeadPlusYByRotateZ, 6.5f)
    , PARAM_INIT(mSLBodyPlusYByRotateZ, 3.5f)
    , PARAM_INIT(mSLRecoverSearchDist, 1000.0f)
    , PARAM_INIT(mSLRecoverSearchDegree, 90.0f)
    , PARAM_INIT(mSLShineAppearOffsetY, 0.0f)
    , PARAM_INIT(mSLCamShakeZeroDist, 4000.0f)
    , PARAM_INIT(mSLCamShakeMaxDist, 500.0f)
    , PARAM_INIT(mSLMotionBlendFrames, 20)
{
	load(mPrmPath);
}

TBossHanachanChangeSaveParams::TBossHanachanChangeSaveParams(const char* path)
    : TParams(path)
    , PARAM_INIT(mSLWalkBckRateMagnif, 0.1f)
    , PARAM_INIT(mSLWalkBckRateMin, 0.3f)
    , PARAM_INIT(mSLWalkAnmMarchSpeed, 10.0f)
    , PARAM_INIT(mSLRunAnmMarchSpeed, 24.0f)
    , PARAM_INIT(mSLMaxMarchSpeed, 24.0f)
    , PARAM_INIT(mSLMarchAccel, 0.02f)
    , PARAM_INIT(mSLMarchDecrease, 0.05f)
    , PARAM_INIT(mSLWalkTurnSpeed, 1.0f)
    , PARAM_INIT(mSLFallDecideRotateZ, 90.0f)
    , PARAM_INIT(mSLWaveFallDownSpeed, 1.1f)
    , PARAM_INIT(mSLFallDecideMinSpeed, 1.0f)
    , PARAM_INIT(mSLSandSlopeForce, 0.05f)
    , PARAM_INIT(mSLMaxRotateZNotSand, 40.0f)
    , PARAM_INIT(mSLRotateZLeanSpeed, 1.0f)
    , PARAM_INIT(mSLRotateZRestorationSpeed, 0.3f)
    , PARAM_INIT(mSLDiffMaxRotateZ, 60.0f)
    , PARAM_INIT(mSLCentrifugalForce, 30.0f)
    , PARAM_INIT(mSLCentrifugalSpeed, 1.0f)
    , PARAM_INIT(mSLWaveVelocity, 200.0f)
    , PARAM_INIT(mSLWaveDecrease, 100.0f)
    , PARAM_INIT(mSLDownFrames, 2000)
    , PARAM_INIT(mSLDamageFrames, 500)
    , PARAM_INIT(mSLNotFallDownFrames, 600)
    , PARAM_INIT(mSLNormalBckFrameDiff, 10)
    , PARAM_INIT(mSLGetUpFrameDiff, 17)
    , PARAM_INIT(mSLSnortFrameDiff, 10)
    , PARAM_INIT(mSLDamageFrameDiff, 10)
    , PARAM_INIT(mSLDeadFrameDiff, 10)
    , PARAM_INIT(mSLParticleProbability, 0.2f)
    , PARAM_INIT(mSLThrowTotalPower, 100.0f)
    , PARAM_INIT(mSLThrowSpeedMin, 20.0f)
    , PARAM_INIT(mSLThrowSpeedMax, 300.0f)
    , PARAM_INIT(mSLThrowMoveDirPower, 20.0f)
    , PARAM_INIT(mSLThrowVecY, 150.0f)
{
	load(mPrmPath);
}
