#ifndef ENEMY_BOSS_HANACHAN_ANM_HPP
#define ENEMY_BOSS_HANACHAN_ANM_HPP

enum EnumBossHanachanAnmKind {
	BOSS_HANACHAN_ANM_UNK0  = 0,
	BOSS_HANACHAN_ANM_UNK1  = 1,
	BOSS_HANACHAN_ANM_UNK9  = 9,
	BOSS_HANACHAN_ANM_UNK12 = 12,
	BOSS_HANACHAN_ANM_UNK16 = 16,
	BOSS_HANACHAN_ANM_UNK17 = 17,
};

enum EnumBossHanachanNerveAnm { };

enum EnumBossHanachanStopMotionBlendOnOff {
	BOSS_HANACHAN_STOP_MOTION_BLEND_OFF = 0,
	BOSS_HANACHAN_STOP_MOTION_BLEND_ON  = 1,
};

#endif
