#!/usr/bin/env python3
"""Rebuild docs/TIMELINE.md from git history.

Every commit that touched PROGRESS.md or config/GMSE01/objects.json is a
snapshot: the linked-unit counts come from objects.json (reliable at every
commit), the matched-code percentages from PROGRESS.md where its table can be
parsed. The report lists one row per snapshot, then per-day rates and a
projection to full source linking from the recent and the overall rate.

    python3 tools/progress-timeline.py            # rewrite docs/TIMELINE.md
    python3 tools/progress-timeline.py --print    # print only
"""
import json
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone

ROOT = subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip()
START = "2026-09-15 08:00"  # first commit of this clone's decomp run (EDT)
TOTAL_UNITS = 732
LIB_PREFIXES = ("JSystem/", "dolphin/", "PowerPC_EABI_Support/", "MetroTRK/", "TRK_MINNOW_DOLPHIN/", "MSL_C", "Runtime", "OdemuExi2/")
OUT = ROOT + "/docs/TIMELINE.md"


def git(*args):
    return subprocess.check_output(["git", "-C", ROOT] + list(args), text=True)


def show(commit, path):
    try:
        return git("show", f"{commit}:{path}")
    except subprocess.CalledProcessError:
        return ""


def parse_progress(text):
    """Return (game_matched, game_linked, all_matched, all_linked) percents or Nones."""
    g = re.search(r"^\| Game \| ([\d.]+)% \| ([\d.]+)% \|", text, re.M)
    a = re.search(r"^\| All \| ([\d.]+)% \| ([\d.]+)% \|", text, re.M)
    if g:
        return (float(g.group(1)), float(g.group(2)),
                float(a.group(1)) if a else None, float(a.group(2)) if a else None)
    old = re.search(r"^\| Game code \|[^|]*\*\*([\d.]+)%\*\*[^|]*\|[^|]*\*\*([\d.]+)%\*\*", text, re.M)
    if old:
        return (float(old.group(1)), float(old.group(2)), None, None)
    return (None, None, None, None)


def game_total(commit):
    return 385


def main():
    log = git("log", "--format=%h %cI", "--reverse", "--", "PROGRESS.md", "config/GMSE01/objects.json")
    rows = []
    for line in log.splitlines():
        h, iso = line.split()
        t = datetime.fromisoformat(iso).astimezone(timezone(timedelta(hours=-4)))
        objs = show(h, "config/GMSE01/objects.json")
        try:
            linked = json.load(__import__("io").StringIO(objs))
        except Exception:
            continue
        n_all = len(linked)
        n_game = sum(1 for x in linked if not x.startswith(LIB_PREFIXES))
        gm, gl, am, al = parse_progress(show(h, "PROGRESS.md"))
        rows.append(dict(h=h, t=t, all=n_all, game=n_game, gm=gm, gl=gl, am=am))
    # carry the last parsable percentages forward so every row prints something
    last = (0.0, 0.0, 0.0)
    for r in rows:
        if r["gm"] is None:
            r["gm"], r["gl"], r["am"] = last
        else:
            if r["am"] is None:
                r["am"] = last[2]
            last = (r["gm"], r["gl"], r["am"])
    t0 = datetime.fromisoformat(START).replace(tzinfo=timezone(timedelta(hours=-4)))
    now = datetime.now(timezone(timedelta(hours=-4)))
    out = []
    out.append("# Progress timeline (GMSE01)\n")
    out.append(f"Generated by `tools/progress-timeline.py` on {now:%Y-%m-%d %H:%M} EDT from the git history of `PROGRESS.md` and `config/GMSE01/objects.json`.")
    out.append(f"Run start: {t0:%Y-%m-%d %H:%M} EDT. Elapsed: {(now - t0).total_seconds() / 3600:.1f} h.\n")
    cur = rows[-1]
    out.append("## Now\n")
    out.append("| | Matched code | Linked units |")
    out.append("| --- | ---: | ---: |")
    out.append(f"| Game | {cur['gm']:.2f}% | {cur['game']} / 385 |")
    out.append(f"| All | {cur['am']:.2f}% | {cur['all']} / {TOTAL_UNITS} |\n")

    # per-day summary
    out.append("## Per day\n")
    out.append("| Day (EDT) | Commits | Game matched at end | Game linked at end | All linked at end | Game links that day |")
    out.append("| --- | ---: | ---: | ---: | ---: | ---: |")
    days = {}
    for r in rows:
        days.setdefault(r["t"].date(), r)  # last row of the day wins below
        days[r["t"].date()] = r
    commits_by_day = {}
    for line in git("log", "--format=%cI", f"--since={t0.isoformat()}").splitlines():
        d = datetime.fromisoformat(line).astimezone(timezone(timedelta(hours=-4))).date()
        commits_by_day[d] = commits_by_day.get(d, 0) + 1
    prev_game = 0
    for d in sorted(days):
        r = days[d]
        out.append(f"| {d} | {commits_by_day.get(d, 0)} | {r['gm']:.2f}% | {r['game']} | {r['all']} | +{r['game'] - prev_game} |")
        prev_game = r["game"]
    out.append("")

    # rates and projection
    def rate(hours):
        since = now - timedelta(hours=hours)
        base = [r for r in rows if r["t"] <= since]
        b = base[-1] if base else rows[0]
        dt = (cur["t"] - b["t"]).total_seconds() / 3600
        if dt <= 0:
            return None
        return dict(hours=dt, game_links=(cur["game"] - b["game"]) / dt, all_links=(cur["all"] - b["all"]) / dt,
                    gm=(cur["gm"] - b["gm"]) / dt)

    out.append("## Rates and projection\n")
    out.append("Linear extrapolations only; the remaining units are the hard ones, so treat every date as a floor, not an estimate.\n")
    out.append("| Window | Game links / h | All links / h | Game matched pts / h | Days to 385 game links | Days to 732 all links |")
    out.append("| --- | ---: | ---: | ---: | ---: | ---: |")
    for label, hours in (("last 12 h", 12), ("last 24 h", 24), ("last 48 h", 48), ("whole run", 10 ** 6)):
        rr = rate(hours)
        if not rr:
            continue
        dg = (385 - cur["game"]) / rr["game_links"] / 24 if rr["game_links"] > 0 else float("inf")
        da = (TOTAL_UNITS - cur["all"]) / rr["all_links"] / 24 if rr["all_links"] > 0 else float("inf")
        out.append(f"| {label} ({rr['hours']:.0f} h) | {rr['game_links']:.2f} | {rr['all_links']:.2f} | {rr['gm']:.3f} | {dg:.1f} | {da:.1f} |")
    out.append("")

    out.append("## Snapshots\n")
    out.append("One row per commit that touched `PROGRESS.md` or `objects.json`.\n")
    out.append("| Time (EDT) | Elapsed h | Commit | Game matched | Game linked | All matched | All linked |")
    out.append("| --- | ---: | --- | ---: | ---: | ---: | ---: |")
    for r in rows:
        el = (r["t"] - t0).total_seconds() / 3600
        gm = f"{r['gm']:.2f}%" if r["gm"] else ""
        am = f"{r['am']:.2f}%" if r["am"] else ""
        out.append(f"| {r['t']:%m-%d %H:%M} | {el:6.1f} | {r['h']} | {gm} | {r['game']} | {am} | {r['all']} |")
    text = "\n".join(out) + "\n"
    if "--print" in sys.argv:
        print(text)
    else:
        open(OUT, "w").write(text)
        print("\n".join(out[:25]))


if __name__ == "__main__":
    main()
