#ifndef CAMERA_CAMERA_MODE_HPP
#define CAMERA_CAMERA_MODE_HPP

// Mode names taken from CPolarSubCamera::mCamKindNameSaveFile (each entry is
// the .prm filename the developers used for that mode's TCamSaveKindParam).
enum ECameraMode {
	CAMERA_MODE_FOLLOW            = 0x0,
	CAMERA_MODE_PARALLEL          = 0x1,
	CAMERA_MODE_MULTI_PLAYER      = 0x2,
	CAMERA_MODE_WALL_JUMP         = 0x3,
	CAMERA_MODE_HIP_ATTACK        = 0x4,
	CAMERA_MODE_ROCKET_JUMP       = 0x5,
	CAMERA_MODE_WIRE              = 0x6,
	CAMERA_MODE_L_NORMAL          = 0x7,
	CAMERA_MODE_MARE_UNDER_GROUND = 0x8,
	CAMERA_MODE_DEFINITE_D2       = 0x9,
	CAMERA_MODE_TALK_E            = 0xA,
	CAMERA_MODE_LEAN_MIRROR       = 0xB,
	CAMERA_MODE_TALK_A            = 0xC,
	CAMERA_MODE_UNDER_GROUND      = 0xD,
	CAMERA_MODE_INDOOR            = 0xE,
	CAMERA_MODE_HANG              = 0xF,
	CAMERA_MODE_WIRE_HANG         = 0x10,
	CAMERA_MODE_SAND_BIRD         = 0x11,
	CAMERA_MODE_HOVERING          = 0x12,
	CAMERA_MODE_JUMP_CODE         = 0x13,
	CAMERA_MODE_DELFINO           = 0x14,
	CAMERA_MODE_CLIMB             = 0x15,
	CAMERA_MODE_FIX_A             = 0x16,
	CAMERA_MODE_FIX_B             = 0x17,
	CAMERA_MODE_FIX_C             = 0x18,
	CAMERA_MODE_FIX_D             = 0x19,
	CAMERA_MODE_FIX_E             = 0x1A,
	CAMERA_MODE_FIX_F             = 0x1B,
	CAMERA_MODE_FIX_G             = 0x1C,
	CAMERA_MODE_FIX_H             = 0x1D,
	CAMERA_MODE_DEFINITE_A        = 0x1E,
	CAMERA_MODE_DEFINITE_B        = 0x1F,
	CAMERA_MODE_DEFINITE_C        = 0x20,
	CAMERA_MODE_DEFINITE_D        = 0x21,
	CAMERA_MODE_DEFINITE_E        = 0x22,
	CAMERA_MODE_DEFINITE_F        = 0x23,
	CAMERA_MODE_DEFINITE_G        = 0x24,
	CAMERA_MODE_DEFINITE_H        = 0x25,
	CAMERA_MODE_EX_MAP_0          = 0x26,
	CAMERA_MODE_TOWER_A           = 0x27,
	CAMERA_MODE_TOWER_B           = 0x28,
	CAMERA_MODE_TOWER_C           = 0x29,
	CAMERA_MODE_SLIDER            = 0x2A,
	CAMERA_MODE_DIVING            = 0x2B,
	CAMERA_MODE_TURBO             = 0x2C,
	CAMERA_MODE_TALK_B            = 0x2D,
	CAMERA_MODE_JET_COASTER       = 0x2E,
	CAMERA_MODE_PARALLEL_B        = 0x2F,
	CAMERA_MODE_SURFING           = 0x30,
	CAMERA_MODE_SWIMMING          = 0x31,
	CAMERA_MODE_CLIMB_JUMP        = 0x32,
	CAMERA_MODE_LOOK_DOWN         = 0x33,
	CAMERA_MODE_RAIL_FENCE        = 0x34,
	CAMERA_MODE_FOLLOW_B          = 0x35,
	CAMERA_MODE_FOLLOW_C          = 0x36,
	CAMERA_MODE_TOWER_D           = 0x37,
	CAMERA_MODE_DELFINO_ATTIC     = 0x38,
	CAMERA_MODE_BOSS_GESO         = 0x39,
	CAMERA_MODE_FIX_I             = 0x3A,
	CAMERA_MODE_DEFINITE_I        = 0x3B,
	CAMERA_MODE_FENCE             = 0x3C,
	CAMERA_MODE_MONTE_FENCE       = 0x3D,
	CAMERA_MODE_MONTE_HANG        = 0x3E,
	CAMERA_MODE_TALK_C            = 0x3F,
	CAMERA_MODE_TALK_D            = 0x40,
	CAMERA_MODE_TOWER_E           = 0x41,
	CAMERA_MODE_DELFINO_B         = 0x42,
	CAMERA_MODE_CANCAN            = 0x43,
	CAMERA_MODE_AQUATIC_TURBO     = 0x44,
	CAMERA_MODE_FOLLOW_D          = 0x45,
	CAMERA_MODE_FOLLOW_E          = 0x46,
	CAMERA_MODE_PARALLEL_C        = 0x47,
	CAMERA_MODE_PARALLEL_D        = 0x48,
	CAMERA_MODE_REPRODUCE_DEMO    = 0x49,

	CAMERA_MODE_INVALID = -1,
};

#endif
